#!/bin/sh -e

DATA_DIR=/tmp/zinstaller-remote

mkdir -p /target/var/lib/
cp -r $DATA_DIR /target/var/lib/

if ! [ -f $DATA_DIR/LICENSE ]
then
    exit 0
fi

LICENSE=`cat $DATA_DIR/LICENSE`
REPO=archive.zentyal.com

SOURCES_DIR=/target/etc/apt/sources.list.d
mkdir -p $SOURCES_DIR
echo "deb https://$LICENSE:lk@$REPO/zentyal-qa 5.0 main" > $SOURCES_DIR/zentyal-qa.list

CONF_DIR=/target/etc/apt/apt.conf.d/
mkdir -p $CONF_DIR
cat >> $CONF_DIR/99zentyal <<EOF
Acquire::https::$REPO {
   Verify-Peer "false";
};
EOF

mkdir -p /target/var/lib/zentyal/
touch /target/var/lib/zentyal/.commercial-edition
echo $LICENSE > /target/var/lib/zentyal/.license

exit 0
