#!/bin/bash

# stop services
SERVICES="amavis spamassassin"
for SERVICE in $SERVICES; do
    service $SERVICE stop || true
done

# move out old amavis conf files
mv /etc/amavis/conf.d /etc/amavis/conf.d.old
mkdir -p /etc/amavis/conf.d
chmod --reference=/etc/amavis/conf.d.old /etc/amavis/conf.d
chown --reference=/etc/amavis/conf.d.old /etc/amavis/conf.d

groups clamav | grep -q amavis
if [ $? != 0 ]; then
  # add clamav user to group amavis. Because it need access to amavis stuff
  addgroup clamav amavis
fi

/usr/share/zentyal-mailfilter/create-spamassassin-db

exit 0;
