#!/usr/bin/perl
use strict;
use warnings;

use EBox;
use EBox::Global;
use EBox::MailVDomainsLdap;
use EBox::MailFilter::VDomainsLdap;
use EBox::Sudo qw(root);
use EBox::UsersAndGroups::User;

sub update
{
    my $users =  EBox::Global->modInstance('users');

    my @controlUsers = (
        {
            user => 'spam',
            givenname => 'Spam',
            surname => 'account',
            surname  => 'spam',
            password => '',
        },
        {
            user => 'ham',
            givenname => 'Ham',
            surname => 'account',
            surname => 'ham',
            password => '',
        },
    );


    foreach my $user_r (@controlUsers) {
        my $username = $user_r->{user};
        my $dn = $users->userDn($username);

        my $user = new EBox::UsersAndGroups::User(dn => $dn);
        unless ($user->exists()) {
            EBox::UsersAndGroups::User->create($user_r, 1);
        }
        else {
            my $uid = $user->get('uidNumber');
            if ($uid > $user->lastUid(1)) {
                die "$user->name is not a system user as it has to be";
            }
        }
    }


    my $vdomainMailfilter = new EBox::MailFilter::VDomainsLdap;
    my @vdomains = _vdomains();
    foreach my $vdomain (@vdomains) {
        $vdomainMailfilter->_addVDomain($vdomain);
    }
}


sub clean
{
    my $vdomainMailfilter = new EBox::MailFilter::VDomainsLdap;
    my @vdomains = _vdomains();
    foreach my $vdomain (@vdomains) {
        $vdomainMailfilter->_delVDomain($vdomain);
    }
}

sub _vdomains
{
    my $vdomainMail       = new EBox::MailVDomainsLdap;
    return $vdomainMail->vdomains();
}

sub usage
{
    print "Usage: $0 update | clean\n";
    exit 1;
}

EBox::init();

unless ($#ARGV == 0) {
    usage();
}

if ($ARGV[0] eq 'update') {
    update();
} elsif ($ARGV[0] eq 'clean') {
    clean();
} else {
    usage();
}

1;
