#!/bin/bash -x

# copy LDAP schemas
cp /usr/share/ebox-mail/*.schema /etc/ldap/schema

# Create certificates for smptd
test -d /etc/postfix/sasl || mkdir -p /etc/postfix/sasl
 /usr/share/ebox-mail/ebox-create-certificate /etc/postfix/sasl/
 mv /etc/postfix/sasl/smtp.key /etc/postfix/sasl/smtpd-key.pem
 mv /etc/postfix/sasl/smtp.cert /etc/postfix/sasl/smtpd.pem

# Create certificates for dovecot
test -d /etc/dovecot/ssl || mkdir -p /etc/dovecot/ssl
/usr/share/ebox-mail/ebox-create-certificate /etc/dovecot/ssl
mv /etc/dovecot/ssl/smtp.cert  /etc/dovecot/ssl/dovecot.pem
mv /etc/dovecot/ssl/smtp.key /etc/dovecot/ssl/dovecot_key.pem
chown root:root /etc/dovecot/ssl/*
chmod 0400 /etc/dovecot/ssl/*



# Generate mail aliases
touch /etc/postfix/main.cf # newaliases fails if no main.cf file is present
newaliases

# regenerate slapd.conf
/usr/share/ebox-usersandgroups/ebox-init-ldap genconfig

# restart slapd
invoke-rc.d slapd restart

# populate ldap
/usr/share/ebox-mail/ebox-mail-ldap update


# restart mail to generate configuration files
invoke-rc.d ebox mail restart


