#!/usr/bin/perl
# Simple script to import time zone 
use strict; 

use constant SASLPATH	=> "/etc/postfix/sasl/";
use constant CERTPATH => "../conf/";

my $cmd = CERTPATH."*.pem " . SASLPATH;

`/bin/cp $cmd`;
