#!/bin/bash -x

# Create certificates for smptd
test -d /etc/postfix/sasl || mkdir -p /etc/postfix/sasl
/usr/share/ebox-mail/ebox-create-certificate /etc/postfix/sasl
cat /etc/postfix/sasl/smtp.cert  /etc/postfix/sasl/smtp.key >  /etc/postfix/sasl/postfix.pem
rm /etc/postfix/sasl/smtp.cert  /etc/postfix/sasl/smtp.key


# Create certificates for dovecot
test -d /etc/dovecot/ssl || mkdir -p /etc/dovecot/ssl
/usr/share/ebox-mail/ebox-create-certificate /etc/dovecot/ssl
cat /etc/dovecot/ssl/smtp.cert  /etc/dovecot/ssl/smtp.key >  /etc/dovecot/ssl/dovecot.pem
rm /etc/dovecot/ssl/smtp.cert  /etc/dovecot/ssl/smtp.key
chown root:root /etc/dovecot/ssl/*
chmod 0400 /etc/dovecot/ssl/*



# Generate mail aliases
touch /etc/postfix/main.cf # newaliases fails if no main.cf file is present
newaliases

# populate ldap
/usr/share/ebox-mail/ebox-mail-ldap update

# restart mail to generate configuration files
invoke-rc.d ebox mail restart
