#!/usr/bin/perl

use strict;

use EBox::Global;
use EBox::MailVDomainsLdap;
use EBox::MailAliasLdap;

EBox::init();

my $global = EBox::Global->getInstance(1);
my $users = $global->modInstance('users');
my $vdomain = new EBox::MailVDomainsLdap;
my $alias = new EBox::MailAliasLdap;

$vdomain->{ldap}->ldapCon;
my $ldap = $vdomain->{ldap}->{ldap};
my $dn = "ou=postfix, " . $vdomain->{ldap}->dn;

my $result = $ldap->add($dn, attr => [
	'ou' => 'postfix',
	'objectClass' => 'top',
	'objectClass' => 'organizationalUnit'
]);

($result->is_error) and warn "Cant initialize postfix leaf.";

my $dn = $vdomain->vdomainDn();

my $result = $ldap->add($dn, attr => [
'ou' => 'vdomains',
'objectClass' => 'top',
'objectClass' => 'organizationalUnit'
]);

($result->is_error) and warn "Cant initialize virtual domains leaf.";

my $dn = $alias->aliasDn();

my $result = $ldap->add($dn, attr => [
	'ou'	=>	'mailalias',
	'objectClass' => 'top',
	'objectClass' => 'organizationalUnit'
]);

($result->is_error) and warn "Cant initialize mail alias leaf.";
