#!/usr/bin/perl

# Copyright (C) 2013 Zentyal S.L.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License, version 2, as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

# This script updates the samba users and groups SIDs to uidNumber and gidNumber
# mappings in the idmap database.

use strict;
use warnings;

use TryCatch::Lite;

use EBox::Global;
use EBox::Samba::User;

EBox::init();

print "Updating users mappings...\n";
my $usersModule = EBox::Global->modInstance('users');
my $ldapUsers = $usersModule->users();
foreach my $user (@{$ldapUsers}) {
    my $uid = $user->get('uid');
    my $uidNumber = $user->get('uidNumber');
    next unless defined $uid and defined $uidNumber;

    my $sambaUser = new EBox::Samba::User(samAccountName => $uid);
    next unless $sambaUser->exists();

    try {
        print "Updating uidNumber mapping for user '$uid' (uidNumber: $uidNumber)\n";
        $sambaUser->setupUidMapping($uidNumber);
    } catch ($error) {
        print "\tError: $error\n";
    }
}
print "\n";

print "Updating groups mappings...\n";
my $ldapGroups = $usersModule->groups();
foreach my $group (@{$ldapGroups}) {
    my $gid = $group->get('cn');
    my $gidNumber = $group->get('gidNumber');
    next unless defined $gid and defined $gidNumber;

    my $sambaGroup = new EBox::Samba::Group(samAccountName => $gid);
    next unless $sambaGroup->exists();

    try {
        print "Updating gidNumber mapping for group '$gid' (gidNumber: $gidNumber)\n";
        $sambaGroup->setupGidMapping($gidNumber);
    } catch ($error) {
        print "\tError: $error\n";
    }
}
print "\n";

print "Done.\n";
