#!/bin/bash

SHARE=$1

if [ -z "$SHARE" ]
then
    echo "Usage: $0 <share_name>"
    exit 1
fi

shopt -s nocaseglob
shopt -s nullglob

for i in /home/samba/shares/$SHARE/{*.jpg,*.jpeg}
do
    USERNAME=$(basename $i | sed -r 's/\.jpe?g$//')
    /usr/share/zentyal-samba/set-thumbnail-photo $USERNAME $i >/dev/null 2>&1
done
