#!/bin/bash

# This script is intended to launch john the ripper and kill it after
# CRACKING_TIME seconds

CRACKING_TIME=21600
GAP=60
readonly CRACKING_TIME GAP

nice john $@ &
JOHN_PID=$!

# Starting up the process
sleep 1

counter=0
while kill -0 $JOHN_PID 2> /dev/null && test $counter -le $CRACKING_TIME
do
    sleep $GAP
    let counter=counter+$GAP
done

kill $JOHN_PID 2> /dev/null || true