#!/bin/bash

PROXY="192.168.2.1:3128"

if [ "x$PASSWORD" != "x" ]
then
    export http_proxy="http://$USERNAME:$PASSWORD@$PROXY/"
else
    export http_proxy="http://$PROXY/"
fi
echo "Using http_proxy=$http_proxy ..."

ERROR=0

for i in `seq 1 5`
do
    [ -f output.html ] && rm output.html

    echo "HTTP request to $HOST"
    wget -t 3 $HOST -O output.html > wget_output 2>&1

    echo "wget output:"
    cat wget_output

    if [ $? = 0 -a -f output.html -a `wc -c output.html | cut -d' ' -f1` -gt 0 ]
    then
        echo "Access allowed."
    else
        echo "Access failed."
        ERROR=`expr $ERROR + 1`
        sleep 2
    fi
done

if [ $ERROR -ge 2 ]
then
    exit 1
else
    exit 0
fi
