#!/usr/bin/perl
#
# Copyright (C) 2010-2013 Zentyal S.L.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License, version 2, as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

use warnings;
use strict;

use ZentyalDesktop::Config qw(ZENTYAL_DESKTOP_DIR CONFIGURED_STAMP);
use ZentyalDesktop::SoftwareConfigurator;

unless (-d ZENTYAL_DESKTOP_DIR) {
    mkdir (ZENTYAL_DESKTOP_DIR);
}

my $server = `grep ^host /etc/ldap.conf | cut -d' ' -f2 | cut -d: -f1`;
chomp ($server);
my $user = $ENV{USER};

ZentyalDesktop::SoftwareConfigurator->configure($server, $user);

system ('touch ' . CONFIGURED_STAMP);

exit 0;
