#!/bin/sh
#
# Copyright (C) 2009-2013 Zentyal S.L.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License, version 2, as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

SERVER=$1

if [ -z $SERVER ]
then
    echo "Usage: $0 <server-address>"
    exit 1
fi

DC=`ldapsearch -x -s base -h $SERVER '(objectclass=*)' namingContexts |
    grep ^namingContexts | cut -d' ' -f2-`

sed -i "s/^host .*$/host $SERVER/" /etc/ldap.conf
sed -i "s/^base .*$/base $DC/" /etc/ldap.conf
for i in Users Computers Groups
do
    sed -i "s/ou=$i,.*one$/ou=$i,$DC?one/" /etc/ldap.conf
done

auth-client-config -a -p zentyal
