Welcome to Debian GNU/Linux PowerPC (CODENAME)

You have the choice of installing your system using one of two
different versions, 'install' or 'install24'.

The 'install' option is the default; it uses version 2.2 of the Linux
kernel and is proven to be stable on most hardware.  The 'install24'
option is based on the 2.4 Linux kernel, and is a bit more
cutting-edge, but it has better support for newer hardware.  If you
have a Power Macintosh computer manufactured in late 2000 or later,
definitely choose 'install24'.

Additionally, there are 'install-safe' and 'install24-safe' options
which you should try if the system fails to boot at all (the typical
symptom is a white screen which doesn't go away).

************************************
If in doubt, just choose 'install', and if that doesn't work, try
'install24', 'install-safe', and 'install24-safe' in that order.
************************************
