#!/usr/bin/perl

use strict;

use EBox::Global;
use EBox::UsersAndGroups;

EBox::init();

my $global = EBox::Global->getInstance();
my $users = $global->modInstance('users');
$users->{ldap}->ldapCon();

sub update
{
	foreach my $user (@{$users->users()}){
		print "Checking user: $username\n";
        if (not $user->get('jabberUid')) {
			print "Adding Jabber account for user $username\n";
            my @objectclasses = $user->get('objectclass');
            push (@objectclass, 'userJabberAccount');

            $user->set('objectclass', \@objectclass, 1);
            $user->set('jabberUid', $user->name(), 1);
            $user->set('jabberAdmin', 'FALSE', 1);
            try {
                $user->save();
            } otherwise {
                warn "Error updating user: $username\n";
            }
		} else {
			print "User $username already has a Jabber account\n";
		}
	}
}

sub clean {
	my $ldap = $users->{ldap};
	foreach my $user (@{$users->users()}){
        $user->delete('jabberUid', 1) if $user->get('jabberUid');
        $user->delete('jabberAdmin', 1) if $user->get('jabberAdmin');

        my @objectclasses = $user->get('objectclass');
        @objectclasses = grep { $_ ne 'userJabberAccount' } @objectclasses;

        $user->set('objectClass', \@objectclasses);
        $user->save();
	}
}

sub usage {
	print "Usage: $0 update | clean\n";
	exit 1;
}

unless ($#ARGV == 0) {
	usage();
}

if ($ARGV[0] eq 'update') {
	update();
} elsif ($ARGV[0] eq 'clean') {
	clean();
} else {
	usage();
}
