#!/usr/bin/perl
use strict;
use warnings;

use EBox;
use EBox::Global;
use EBox::Config;

EBox::init();

my @mods = @{EBox::Global->modInstances()};

for my $mod (@mods) {
    $mod->consolidateReportInfo();
}

1;
