#!/usr/bin/perl
# Copyright (C) 2011 eBox Technologies S.L.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License, version 2, as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

use strict;
use warnings;

use EBox;
use EBox::Config;
use EBox::Global;
use Error qw(:try);

my ($modname, $version) = @ARGV;

EBox::init();

my $module = EBox::Global->modInstance($modname);

try {
    $module->initialSetup($version);
} otherwise {
    failed("Initial setup for $modname failed");
};

# Run migrations only if upgrading
if ($version) {
    $module->migrate($version);
}

# We are finished for non-service modules
exit 0 unless $module->isa('EBox::Module::Service');

# Restart service always except during the first install
unless (-f EBox::Config::home() . '.first') {
    try {
        $module->restartService();
    } otherwise {
        warning("Restart for $modname failed");
    };
}

exit 0;

sub failed
{
    my ($msg) = @_;

    EBox::error($msg);
    print STDERR "$msg\n";
    exit 1;
}

sub warning
{
    my ($msg) = @_;

    EBox::warn($msg);
    print STDERR "Warning: $msg\n";
}
