#!/usr/bin/perl

use strict;
use warnings;

use lib '../../..';

use EBox;
use EBox::Util::Nmap;
use Data::Dumper;

my ($host, $proto, $port) = @ARGV;

EBox::init();
my $res = EBox::Util::Nmap::singlePortScan(
        host => $host,
        protocol => $proto,
        port  => $port
        );

print Dumper($res);

1;

