#!/bin/bash

TESTFILE=/tmp/anste-openvpn-ready-$$

cd $CLIENT

openvpn --script-security 2 --config foobar-server-client.conf --daemon --route-up "/bin/touch $TESTFILE" --log $TESTFILE.log

for i in `seq 1 20`
do
    if [ -r $TESTFILE ]
    then
        echo "OpenVPN connected"
        break
    else
        sleep 1
    fi
done

cat $TESTFILE.log

rm $TESTFILE $TESTFILE.log

echo "Expecting foo on $HOST:1100"

for i in `seq 1 30`
do
    nc $HOST 1100 | grep "foo"
    if [ $? != 0 ]
    then
        echo "$i try"
        sleep 1
    else
	echo "Succes"
        exit 0
    fi
done

exit 1
