#!/bin/sh

USER_NAME=`getent passwd uid 1000 | cut -d: -f1`
DIR=/home/$USER_NAME

sed -i "s/#auto_login.*/auto_login\tyes/" /etc/slim.conf
sed -i "s/#default_user.*/default_user\t$USER_NAME/" /etc/slim.conf

cp /var/tmp/ebox/ebox-xsession $DIR/.xsession
chmod +x $DIR/.xsession
chown $USER_NAME:$USER_NAME $DIR/.xsession

mkdir $DIR/.mozilla
cp -r /var/tmp/ebox/ebox-firefox-profile $DIR/.mozilla/firefox
chown -R $USER_NAME:$USER_NAME $DIR/.mozilla
chmod -R +w $DIR/.mozilla

PROFILE=$DIR/.mozilla/firefox/ebox.default
CERT=/var/lib/ebox/conf/ssl/ssl.cert
ID='eBox Server'
certutil -d $PROFILE -A -n "$ID" -t ',,' -i $CERT
/var/tmp/ebox/ebox-cert-override > $PROFILE/cert_override.txt

DESKTOP=`su $USER_NAME -c "xdg-user-dirs DESKTOP"`
mv /var/tmp/ebox/Desktop/* $DESKTOP/

mv /var/tmp/ebox/rc.local /etc/rc.local
rm -rf /var/tmp/ebox

exit 0
