#!/bin/sh

USER_NAME=`getent passwd uid 1000 | cut -d: -f1`
DIR=/home/$USER_NAME

sed -i "s/.*autologin=.*/autologin=$USER_NAME/" /etc/lxdm/default.conf
sed -i "s/theme=.*/theme=Zentyal/" /etc/lxdm/default.conf

cp /var/tmp/ebox/zentyal-session /usr/local/bin
chmod +x /usr/local/bin/zentyal-session
echo "@/usr/local/bin/zentyal-session" >> /etc/xdg/lxsession/LXDE/autostart

if [ -f /var/tmp/ebox/.disaster-recovery ]
then
    echo "$USER_NAME ALL = NOPASSWD:/usr/share/ebox-ebackup/restore-tool" >> /etc/sudoers
fi

echo "mode: off" > $DIR/.xscreensaver
echo "selected: -1" >> $DIR/.xscreensaver
chown $USER_NAME:$USER_NAME $DIR/.xscreensaver

mkdir $DIR/.mozilla
cp -r /var/tmp/ebox/ebox-firefox-profile $DIR/.mozilla/firefox
chown -R $USER_NAME:$USER_NAME $DIR/.mozilla
chmod -R +w $DIR/.mozilla

PROFILE=$DIR/.mozilla/firefox/ebox.default
CERT=/var/lib/ebox/conf/ssl/ssl.cert
ID='eBox Server'
certutil -d $PROFILE -A -n "$ID" -t ',,' -i $CERT
/var/tmp/ebox/ebox-cert-override > $PROFILE/cert_override.txt

# Copy LXDM theme
mv /var/tmp/ebox/lxdm-zentyal/background.png /usr/share/backgrounds/default.png
mv /var/tmp/ebox/lxdm-zentyal /usr/share/lxdm/themes/Zentyal
# Copy icon and wallpaper
mv /var/tmp/ebox/lxde-zentyal/*.png /usr/share/pixmaps/

# lxde setup
DESKTOP=`su $USER_NAME -c "xdg-user-dir DESKTOP"`
mkdir -p $DESKTOP
mv /var/tmp/ebox/lxde-zentyal/Desktop/zentyal.desktop /usr/share/applications/
mv /var/tmp/ebox/lxde-zentyal/zentyal-logout.desktop /usr/share/applications/
mv /var/tmp/ebox/lxde-zentyal/zentyal-logout /usr/bin/
ln -sf /usr/bin/zentyal-logout /usr/local/bin/lxde-logout
ln -sf /usr/share/applications/zentyal.desktop $DESKTOP/zentyal.desktop
mv /var/tmp/ebox/lxde-zentyal/Desktop/* $DESKTOP/
PANELS_DIR=$DIR/.config/lxpanel/LXDE/panels
mkdir -p $PANELS_DIR
mv /var/tmp/ebox/lxde-zentyal/bottom $PANELS_DIR/
sed -i "s/DESKTOP_PATH/$DESKTOP/" $PANELS_DIR/bottom
PCMANFM_DIR=$DIR/.config/pcmanfm
mkdir -p $PCMANFM_DIR
mv /var/tmp/ebox/lxde-zentyal/main.lxde $PCMANFM_DIR/
chown -R $USER_NAME:$USER_NAME $DESKTOP
chown -R $USER_NAME:$USER_NAME $DIR/.config

mv /var/tmp/ebox/second-boot.sh /etc/rc.local

initctl emit zentyal-lxdm

exit 0
