#!/bin/bash

if [ -f /var/tmp/zentyal/.disaster-recovery ]
then
    sudo /usr/share/zentyal-ebackup/restore-tool
    rm /var/tmp/zentyal/.disaster-recovery
fi

firefox https://localhost &

xset s off
xset -dpms
xset s noblank
