#!/usr/bin/perl

use Mail::IMAPClient;

$imap = new Mail::IMAPClient( Server => $ENV{SERVER},
                              User => 'eboxtest@foobar',
                              Password => 'eboxtest');

if (not $imap->IsConnected()) {
        print "Authentication failed\n";
        exit 1;
} else {
        print "Authentication OK\n";
}

exit 0;
