#!/bin/bash

# stop daemons 
invoke-rc.d squid stop
invoke-rc.d dansguardian stop || true # if dansguardian has not been configured 
                                      # it will fail always the first time
