#!/usr/bin/perl

# Copyright (C) 2009 eBox Technologies S.L.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License, version 2, as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

# Description:
#
#  This script is intended to unsubscribe this eBox from CC, that is,
#  stop VPN connection and remove every remote services subcription
#  data

use EBox;
use EBox::Global;
use Getopt::Long;
use Pod::Usage;

my $usage = 0;
my $correct = GetOptions(
    "usage|help" => \$usage,
   );

if ( $usage or (not $correct)) {
    pod2usage(1);
}

EBox::init();
my $rs = EBox::Global->modInstance('remoteservices');

my $rv = $rs->unsubscribe();
if ( $rv ) {
    print STDOUT "Unsubscription process was done\n";
}

1;

__END__

=head1 NAME

ebox-unsubscribe - Remove every data related to remote subscribed services

=head1 SYNOPSIS

ebox-unsubscribe [--usage|help]

 Options:
   -- usage|help  Print this help and exit

=cut
