#!/usr/bin/perl

# Copyright (C) 2008-2010 eBox Technologies S.L.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License, version 2, as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

# Description:
#
#  This script is intended to reload the bundle from eBox Control
#  Center if the host is subscribed to

use EBox;
use EBox::Gettext;
use EBox::Global;
use Error qw(:try);
use Getopt::Long;
use Pod::Usage;

my ($usage, $force) = (0, 0);
my $correct = GetOptions(
    "usage|help" => \$usage,
    "force"      => \$force,
   );

if ( $usage or (not $correct)) {
    pod2usage(1);
}

EBox::init();
my $rs = EBox::Global->modInstance('remoteservices');

try {
    my $rv = $rs->reloadBundle($force);
    if ( $rv == 0 ) {
        print STDERR __('Cannot reload the bundle since eBox is not connected but subscribed') . "\n";
    } elsif ( $rv == 1 ) {
        print STDOUT __('Bundle reload successfully') . "\n";
    } elsif ( $rv == 2 ) {
        print STDOUT __('Bundle reload was not possible either because is already the  latest available version or because the ebox-remoteservices module is outdated') . "\n";
    }
} catch EBox::Exceptions::External with {
    # Bundle reload it is only possible with a subscribed eBox
    ;
};

1;

__END__

=head1 NAME

ebox-reload-bundle - Reload bundle sent by eBox Control Center

=head1 SYNOPSIS

ebox-reload-bundle [--usage|help] [--force]

 Options:
   -- usage|help  Print this help and exit

   -- force       Force to reload the bundle although eBox may have the latest available version

This script "must" be called only from the post-installation script and crontab

=cut
