#!/usr/bin/perl

# Copyright (C) 2009 eBox Technologies S.L.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License, version 2, as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

# Description:
#
#  This script is intended to notify CC with new monitoring stats. It
#  will send a tarball containing the whole monitoring stats the first
#  time, if there is already a tarball, a delta is sent using *xdelta*
#  tool

use Archive::Tar;

use EBox;
use EBox::Config;
use EBox::Exceptions::Command;
use EBox::Monitor::Configuration;
use EBox::RemoteServices::Configuration;
use EBox::RemoteServices::Monitor;
use EBox::Sudo;

use Error qw(:try);
use File::Temp;
use Getopt::Long;
use Pod::Usage;

my @fileList = ();
my $usage = 0;
my $correct = GetOptions(
    "usage|help" => \$usage,
   );

if ( $usage or (not $correct)) {
    pod2usage(1);
}

EBox::init();

my $rrdDir = EBox::Monitor::Configuration::RRDBaseDirPath();

my $currentTar = new File::Temp(DIR => EBox::Config::tmp());
try {
    EBox::Sudo::command(
        'tar cf ' . $currentTar->filename() . " $rrdDir"
       );
} catch EBox::Exceptions::Command with {
    my ($exc) = @_;
    print STDERR "$exc\n";
};

my $monSrv = new EBox::RemoteServices::Monitor();
my $retValue = 1;
my $oldTar = EBox::RemoteServices::Configuration::OldTarLocation();
if ( -r $oldTar and -f $oldTar ) {
    my $deltaFile = new File::Temp(DIR => EBox::Config::tmp());
    EBox::Sudo::command(
        "xdelta3 -fe -s $oldTar " . $currentTar->filename() . ' ' . $deltaFile->filename()
       );
    $retValue = $monSrv->sendDelta($deltaFile->filename());
} else {
    $retValue = $monSrv->sendAll($currentTar->filename());
}

if ($retValue) {
    EBox::Sudo::command(
        'mv ' . $currentTar->filename() . " $oldTar"
       );
}

1;

__END__

=head1 NAME

ebox-notify-mon-stats - Notify monitoring stats to CC

=head1 SYNOPSIS

ebox-notify-mon-stats [--usage|help]

 It will send a tar containing the monitoring stats to CC. A delta file
 using xdelta3 tool if there is already a tar file created previously

 Options:
   -- usage|help  Print this help and exit

=cut

