#!/usr/bin/python
# Copyright (C) 2009-2010 eBox Technologies S.L.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the Lesser GNU General Public License as
# published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# Lesser GNU General Public License for more details.
#
# You should have received a copy of the Lesser GNU General Public
# License along with This program; if not, write to the
#	Free Software Foundation, Inc.,
#	59 Temple Place, Suite 330,
#	Boston, MA  02111-1307
#	USA

from sys import argv
#from socket import *
from os import chdir
from glob import glob
from ebox_pwdsync_common import get_queue_path

QUEUE_PATH = get_queue_path()

username = argv[1]
password = argv[2]

chdir(QUEUE_PATH)
existingFiles = glob('*')
lastNum = 0
if existingFiles:
    lastNum = sorted(map(int, existingFiles), reverse=True)[0]
newFile = str(lastNum + 1)
print "Creating file: " + newFile

f = open(newFile, 'w')
f.write(username + '\n')
f.write(password + '\n')
f.close()
