#!/usr/bin/perl
# Copyright (C) 2009 EBox Technologies S.L.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License, version 2, as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

use strict;
use warnings;

my $size = $ENV{SIZE};
defined $size or
    die "missing env parameter: SIZE";

# check more than the squid ocnfig file!
my $status = `status ebox.squid`;
if (not $status =~ m/running/) {
    die 'ebox.squid service not running';
}



my @grepOutput = `grep $size /etc/squid/squid.conf`;
if ($? != 0) {
    die 'not found new cache size in squid configuration file';
}

my $found = 0;
foreach my $line (@grepOutput) {
    if ($line =~ m/cache_dir.*\s$size/) {
        print "cache_dir directive with new size found\n";
        print $line;
        $found = 1;
        last;
    }
}

if (not $found) {
    die "no cache_dir directive with new size found";
}

1;
