#!/bin/bash

#DEBHELPER#

case "$1" in
	configure)

		kill `pidof gconfd-2` >/dev/null 2>&1 || true

		# create spamassassin directory 
		EBOX_HOME=`perl -e'my @pwInfo = getpwnam("ebox"); print $pwInfo[7]; 1'`
		SA_DIR=$EBOX_HOME/.spamassassin
		test -d $SA_DIR || mkdir $SA_DIR
		chown -R amavis.amavis $SA_DIR

        # restart module
		invoke-rc.d ebox mailfilter restart

        # restart apache
        invoke-rc.d ebox apache restart || true

esac



exit 0


