#!/bin/bash

case "$1" in
	remove)
		kill `pidof gconfd-2` >/dev/null 2>&1 || true

		/usr/bin/ebox-clean-gconf mailfilter || true

		# remove  runit services
		RUNIT_SERVICE='clamd spamd amavisd-new'
		for  SERVICE in $RUNIT_SERVICE; do
		    # it must be already down but for prevention..
		    runsvctrl d /var/service/$SERVICE

		    rm /var/service/$SERVICE
		    rm -rf  /etc/runit/$SERVICE
		done
 		

		;;		
esac

#DEBHELPER#
