#!/bin/bash

# create log tables
/usr/share/zentyal/ebox-sql-table add mailfilter_pop /usr/share/zentyal/sqllog/mailfilter_pop.sql
/usr/share/zentyal/ebox-sql-table add mailfilter_pop_report /usr/share/zentyal/sqllog/mailfilter_pop_report.sql
/usr/share/zentyal/ebox-sql-table-with-time-period add mailfilter_pop_traffic /usr/share/zentyal/sqllog/mailfilter_pop_traffic.sql
/usr/share/zentyal/ebox-sql-table add mailfilter_smtp /usr/share/zentyal/sqllog/mailfilter_smtp.sql
/usr/share/zentyal/ebox-sql-table add mailfilter_smtp_report /usr/share/zentyal/sqllog/mailfilter_smtp_report.sql
/usr/share/zentyal/ebox-sql-table-with-time-period add mailfilter_smtp_traffic /usr/share/zentyal/sqllog/mailfilter_smtp_traffic.sql

exit 0
