#!/bin/sh

bash autogen.sh
./configure --disable-runtime-tests
cd po
make update-po
if [ $? != 0 ]
then
echo "Error updating po files for package $i"
exit 1
fi
cd ..
make maintainer-clean
rm -rf config
