#!/bin/bash

# Function to show usage instructions
show_usage() {
    echo -e "Usage:\033[32m\t$0 <modulename> <your name> <email>\033[0m\n"
    echo -e "Example:\033[32m MyModule \"Packaging Developer\" pkg-team@yourcompany.com\033[0m\n"
    echo -e "\033[33mNote: Module should not contain '-' or spaces\033[0m"
    exit 1
}

# Check for the minimum number of arguments
if [ $# -lt 3 ]; then
    show_usage
fi

# Assign input parameters to variables
MODULENAME=$1
DEBFULLNAME=$2
DEBEMAIL=$3

# Convert module name to lowercase
LOWER_MODULENAME=$(echo "$MODULENAME" | tr '[:upper:]' '[:lower:]')

# Check if the module name contains invalid characters
if [[ "$MODULENAME" =~ [^a-zA-Z0-9_] ]]; then
    echo -e "\n\033[31mError: Module name contains invalid characters. Only alphanumeric characters and underscores are allowed.\n\033[0m"
    show_usage
fi

# Check if the email address is valid
if ! [[ "$DEBEMAIL" =~ ^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$ ]]; then
    echo -e "\n\033[31mError: Invalid email address.\n\033[0m"
    show_usage
fi

# Set the destination directory name
DESTDIR=$LOWER_MODULENAME

# Get distribution codename and Zentyal version
DIST=$(lsb_release -c -s)
VERSION=$(perl -e 'use EBox::Config;print EBox::Config::version()')

# Ensure DESTDIR is the lowercase version of MODULENAME
PKGNAME=$(basename "$DESTDIR")

# Create necessary directories
mkdir -p "$DESTDIR/schemas"
mkdir -p "$DESTDIR/src/EBox/$MODULENAME/Model"
mkdir -p "$DESTDIR/stubs"
mkdir -p "$DESTDIR/src/scripts"
mkdir -p "$DESTDIR/debian"
mkdir -p "$DESTDIR/debian/source"

# Create schemas YAML file
cat >$DESTDIR/schemas/$PKGNAME.yaml <<EOF
class: EBox::$MODULENAME

models:
    - Settings
EOF

# Create main Perl module
cat >$DESTDIR/src/EBox/$MODULENAME.pm <<EOF
package EBox::$MODULENAME;

use base qw(EBox::Module::Service);

use strict;
use warnings;

use EBox::Global;
use EBox::Gettext;
use EBox::Sudo;

my \$CONFFILE = '/tmp/FIXME.conf';

# Method: _create
#
# Overrides:
#
#       <Ebox::Module::Base::_create>
#
sub _create
{
    my \$class = shift;

    my \$self = \$class->SUPER::_create(
        name => '$PKGNAME',
        printableName => __('$MODULENAME'),
        @_
    );

    bless (\$self, \$class);

    return \$self;
}

# Method: menu
#
# Overrides:
#
#       <EBox::Module::menu>
#
sub menu
{
    my (\$self, \$root) = @_;

    my \$item = new EBox::Menu::Item(
        url => '$MODULENAME/View/Settings',
        text => \$self->printableName(),
        separator => 'Core',
        order => 1
    );

    \$root->add(\$item);
}

# Method: _daemons
#
# Overrides:
#
#       <EBox::Module::Service::_daemons>
#
sub _daemons
{
    my \$daemons = [
# FIXME: here you can list the daemons to be managed by the module
#        for upstart daemons only the 'name' attribute is needed
#
#        {
#            name => 'service',
#            type => 'init.d',
#            pidfiles => ['/var/run/service.pid']
#        },
    ];

    return \$daemons;
}

# Method: _setConf
#
# Overrides:
#
#       <EBox::Module::Base::_setConf>
#
sub _setConf
{
    my (\$self) = @_;

    my \$settings = \$self->model('Settings');
    my \$booleanValue = \$settings->value('booleanField');
    my \$textValue = \$settings->value('textField');

    my @params = (
        boolean => \$booleanValue,
        text => \$textValue,
    );

    \$self->writeConfFile(
        \$CONFFILE,
        "$PKGNAME/service.conf.mas",
        \@params,
        { uid => '0', gid => '0', mode => '644' }
    );
}

1;
EOF


cat >$DESTDIR/src/EBox/$MODULENAME/Model/Settings.pm <<EOF
package EBox::$MODULENAME::Model::Settings;

use base 'EBox::Model::DataForm';

use strict;
use warnings;

use EBox::Gettext;

use EBox::Types::Text;
use EBox::Types::Boolean;

# Method: _table
#
# Overrides:
#
#       <EBox::Model::DataTable::_table>
#
sub _table
{
    my (\$self) = @_;

    my @fields = (
        new EBox::Types::Boolean(
            fieldName => 'booleanField',
            printableName => __('Example boolean field'),
            editable => 1,
            help => __('This field is an example.'),
        ),
        new EBox::Types::Text(
            fieldName => 'textField',
            printableName => __('Example text field'),
            editable => 1,
            size => '8',
            help => __('This field is another example.'),
        ),
    );

    my \$dataTable =
    {
        tableName => 'Settings',
        printableTableName => __('Settings'),
        pageTitle => \$self->parentModule()->printableName(),
        defaultActions => [ 'editField' ],
        modelDomain => '$MODULENAME',
        tableDescription => \@fields,
        help => __('This is the help of the model'),
    };

    return \$dataTable;
}

1;
EOF

# Create script to enable the module
cat >$DESTDIR/src/scripts/enable-module <<EOF
#!/bin/bash

set -e

### Actions to be executed when enabling the module ###

exit 0
EOF

# Create script for initial setup
cat >$DESTDIR/src/scripts/initial-setup <<EOF
#!/bin/bash

set -e

### Actions to be executed when installing the module for the first time ###

exit 0
EOF

# Create service configuration template
cat >$DESTDIR/stubs/service.conf.mas <<EOF
<%args>
    \$boolean
    \$text
</%args>

boolean = <% \$boolean %>
text = "<% \$text %>"
EOF

# Create post-removal script for Debian package
cat >$DESTDIR/debian/zentyal-$PKGNAME.postrm <<EOF
#!/bin/bash

set -e

#DEBHELPER#

case "\$1" in
    remove)
        dpkg-trigger --no-await zentyal-core
    ;;
    purge)
        /usr/share/zentyal/purge-module $PKGNAME
    ;;
esac

exit 0
EOF

# Create post-installation script for Debian package
cat >$DESTDIR/debian/zentyal-$PKGNAME.postinst <<EOF
#!/bin/bash

set -e

#DEBHELPER#

case "\$1" in
    configure)
        /usr/share/zentyal/initial-setup $PKGNAME \$2
        dpkg-trigger --no-await zentyal-core
    ;;
esac

exit 0
EOF

# Create Debian rules file
cat >$DESTDIR/debian/rules <<EOF
#!/usr/bin/make -f

include /usr/share/zbuildtools/1/rules/zentyal.mk
EOF



# Create changelog for module
cat >$DESTDIR/ChangeLog <<EOF
$VERSION

	+ Initial release

EOF


# Create changelog for Debian package
cat >$DESTDIR/debian/changelog <<EOF
zentyal-$PKGNAME ($VERSION~1) $DIST; urgency=low

  * New upstream release

 -- $DEBFULLNAME <$DEBEMAIL>  $(date +"%a, %d %b %Y %T %z")
 
EOF


# Create control file for Debian package
cat >$DESTDIR/debian/control <<EOF
Source: zentyal-$PKGNAME
Maintainer: $DEBFULLNAME <$DEBEMAIL>
Section: web
Priority: optional
Build-Depends: debhelper (>= 7.0.0), cdbs
Standards-Version: $VERSION
XSBC-Original-Maintainer: $VERSION
Homepage: http://www.zentyal.org/

Package: zentyal-$PKGNAME
Architecture: all
Depends: zentyal-core (>= $VERSION~1), \${misc:Depends}
Description: Zentyal - $MODULENAME module
 Zentyal is a Linux small business server that can act as
 a Gateway, Unified Threat Manager, Office Server, Infrastructure
 Manager, Unified Communications Server or a combination of them. One
 single, easy-to-use platform to manage all your network services.
 .
 FIXME: description goes here.
EOF

# Set compatibility level and source format
echo 10 > "$DESTDIR/debian/compat"
echo '1.0' > "$DESTDIR/debian/source/format"

# Make scripts executable
chmod +x "$DESTDIR/debian/rules"
chmod +x "$DESTDIR/debian/zentyal-$PKGNAME.postinst"
chmod +x "$DESTDIR/debian/zentyal-$PKGNAME.postrm"

# Print final instructions
echo "To build the package, change the directory using: cd $DESTDIR"
echo "Use \"dch -i\" to update your package version and changelog"
echo "Execute package builder using: zentyal-package"
