#!/bin/sh

cd work

mkdir -p image/{casper,isolinux,install}

cp chroot/boot/vmlinuz-2.6.**-**-generic image/casper/vmlinuz
cp chroot/boot/initrd.img-2.6.**-**-generic image/casper/initrd.gz

cp /usr/lib/syslinux/isolinux.bin image/isolinux/

#cp /boot/memtest86+.bin image/install/memtest
cp /boot/sbm.img image/install/

cp ../templates/isolinux.txt image/isolinux/
cp ../templates/splash.rle image/isolinux/
cp ../templates/isolinux.cfg image/isolinux/

cd -
