#!/bin/sh

cwd=`pwd`

cd work

cp ../templates/README.diskdefines image/

touch image/ubuntu

mkdir image/.disk
cd image/.disk
touch base_installable
echo "full_cd/single" > cd_type
# FIXME: Modify this
echo 'Ubuntu 9.10 "Karmic Koala Remix" - i386 (20090429)' > info
echo "http//ubuntu-rescue-remix.org" > release_notes_url

cd ..

sudo sh -c 'find . -type f -print0 | xargs -0 md5sum | grep -v "\./md5sum.txt" > md5sum.txt'

cd $cwd
