#!/bin/sh

# FIXME: Change this
IMAGE_NAME="foobar"

cd work/image

sudo mkisofs -r -V "$IMAGE_NAME" -cache-inodes -J -l -b isolinux/isolinux.bin -c isolinux/boot.cat -no-emul-boot -boot-load-size 4 -boot-info-table -o ../ubuntu-remix.iso .

cd -
