#!/bin/bash

adduser --system --no-create-home vmail

PASSWD_FILE='/var/lib/zentyal/conf/ebox-zarafa.passwd'

if [ -s $PASSWD_FILE ]
then
    PASSWD=`cat $PASSWD_FILE`
else
    PASSWD=`tr -dc A-Za-z0-9 < /dev/urandom | head -c8`
    echo -n $PASSWD > $PASSWD_FILE
fi

echo "DROP DATABASE IF EXISTS zarafa;
CREATE DATABASE zarafa;
GRANT ALL ON zarafa.* TO 'zarafa'@'localhost' IDENTIFIED BY \"$PASSWD\";
FLUSH PRIVILEGES;" | mysql --defaults-file=/etc/mysql/debian.cnf

mkdir -p /etc/zarafa/ssl
/usr/share/zentyal/ebox-create-certificate /etc/zarafa/ssl

exit 0
