#!/bin/bash

#DEBHELPER#

case "$1" in
    configure)
        kill `pidof gconfd-2` >/dev/null 2>&1 || true

        # Migrate data if needed
        /usr/share/ebox/ebox-migrate /usr/share/ebox-monitor/migration/

        # Restart eBox apache
        invoke-rc.d ebox apache restart || true
        # Restart the module itself
        invoke-rc.d ebox monitor restart || true

    ;;
esac



exit 0
