#!/bin/sh

. /usr/share/debconf/confmodule

URL=archive.zentyal.com/zentyal-qa/

DATA_DIR=/tmp/zinstaller-remote

mkdir -p $DATA_DIR

while true
do
    db_input high zinstaller-remote/license
    db_go
    db_get zinstaller-remote/license
    LICENSE="$RET"

    if wget --user=$LICENSE --password=lk $URL -O- | grep Index
    then
        break
    fi

    db_input high zinstaller-remote/auth_failed
    db_go
done

db_input high zinstaller-remote/auth_ok
db_go

echo $LICENSE > $DATA_DIR/REGISTER_USERNAME
echo $LICENSE > $DATA_DIR/REGISTER_PASSWORD

touch $DATA_DIR/COMMERCIAL_EDITION

exit 0
