#!/bin/bash

set -e

# the path where your backups are (without trailing slash)
BACKUP=/mnt/backup/ebox-backup
# the path where your backups logs are
LOG=/mnt/backup/ebox-backup.log
# how many days do you want to keep rotated incremental backups
MAXAGE=90

## pre-commands
#mkdir -p /mnt/backup
#mount -t ext3 /dev/sdb1 /mnt/backup

MODE=700
OWNER=root
GROUP=root

mkdir -p $BACKUP
chmod $MODE $BACKUP
chown $OWNER:$GROUP $BACKUP

# ldap and postgresql database dumps
DUMP=/var/backups/ebox
mkdir -p $DUMP
chmod $MODE $DUMP
chown $OWNER:$GROUP $DUMP
slapcat 2>/dev/null | gzip -c > $DUMP/slapd.ldif.gz
sudo -u ebox pg_dump eboxlogs | gzip -c > $DUMP/pg.sql.gz

rdiff-backup --exclude $BACKUP --exclude /dev --exclude /proc --exclude /sys / $BACKUP/ > $LOG
if [ $? -eq 0 ]; then
    rdiff-backup --remove-older-than $MAXAGE --force $BACKUP/ > $LOG
    rm -f $BACKUP/rdiff-backup.err
else
    echo $? > $BACKUP/rdiff-backup.err
fi

## post-commands
#umount /mnt/backup
