#!/bin/bash
echo "Please, choose the architecture:"
select arch in i386 amd64;
do
    if [ $arch ]; then
        echo "Building $arch image..."
        ltsp-build-client --arch $arch --purge-chroot;
        service nbd-server restart
        break;
    fi
done
