#!/bin/bash
echo "Please, choose the architecture:"
select arch in i386 amd64;
do
    if [ $arch ]; then
        echo -n "Enter the application names separated by spaces: "
        read PACKAGES

        echo "Installing applications into $arch image..."

        CHROOT_DIR=/opt/ltsp/$arch
        chroot $CHROOT_DIR mount -t proc /proc /proc

        chroot $CHROOT_DIR apt-get update
        sudo chroot $CHROOT_DIR env LTSP_HANDLE_DAEMONS=false apt-get -y install $PACKAGES

        umount /opt/ltsp/$arch/proc

        ltsp-update-image --arch $arch

        break;
    fi
done
