#!/usr/bin/perl

use EBox;
use EBox::Global;

use strict;
use warnings;

my $SERVICE = $ENV{SERVICE};

my $module = EBox::Global->modInstance($SERVICE);

print "Checking if module $SERVICE is running...\n";

if ($module->isRunning()) {
    print "Running. Test OK\n";
    exit 0;
} else {
    print "Not running. Test FAILED\n";
    exit 1;
}
