#!/bin/bash

# stop cups
invoke-rc.d cupsys stop

# create /etc/cups/printers.conf if it does not exist
if [ ! -e /etc/cups/printers.conf ]; then
    touch /etc/cups/printers.conf
    chmod 600 /etc/cups/printers.conf
    chown root.lp /etc/cups/printers.conf
fi

# create log table
/usr/share/ebox/ebox-sql-table add jobs /usr/share/ebox/sqllog/printers.sql	

# create spool
if [ ! -d /var/spool/samba ]; then
    mkdir /var/spool/samba 
    chown nobody:nogroup /var/spool/samba
    chmod a+rwt /var/spool/samba
fi

# Set permissions for printer drivers
chown -R root:512 /var/lib/samba/printers
chmod -R g+w /var/lib/samba/printers

# Allow raw printing
sed 's:#application/octet-stream:application/octet-stream:' /etc/cups/mime.convs


