#!/usr/bin/perl
foreach $item (@ARGV){        
	open (FH, "<", $item);        
	foreach $line(<FH>){                
		while ($line =~ s/(__[xd]?)\(([\'\"])(.+?)\2//){
			print $1 . '("' . $3 . '"); '; print "\n";
		}        
		print "\n";
	}        
	close (FH);
}
