#!/bin/bash

#DEBHELPER#

create_tables()
{
    /usr/share/ebox/ebox-sql-table add remoteservices_passwd_report /usr/share/ebox/sqllog/remoteservices_passwd_report.sql
    /usr/share/ebox/ebox-sql-table add remoteservices_passwd_users /usr/share/ebox/sqllog/remoteservices_passwd_users.sql
    /usr/share/ebox/ebox-sql-table add remoteservices_passwd_users_report /usr/share/ebox/sqllog/remoteservices_passwd_users_report.sql

}

case "$1" in
    configure)
        # Migrate data if needed
        /usr/share/ebox/ebox-migrate /usr/share/ebox-remoteservices/migration/

        # Create DB tables if required
        create_tables

        if [ -n "$2" ]; then
            /usr/share/ebox/ebox-reload-bundle
        fi

        if [ ! -e /var/lib/ebox/tmp/upgrade-from-CC ]; then
            invoke-rc.d ebox remoteservices restart
        fi

        dpkg-trigger --no-await ebox

    ;;
esac



exit 0
