#!/usr/bin/perl
use strict;
use warnings;

use EBox;
use EBox::Global;

EBox::init();

my $users = EBox::Global->modInstance('users');
my $slaves = $users->listSlaves();
for my $slave (@{$slaves}) {
    print $slave->{'hostname'} . ':' . $slave->{'port'} . "\n";
}
