#!/bin/bash

REGISTER_DATA=/var/lib/zinstaller-remote

if [ -f $REGISTER_DATA/REGISTER_USERNAME ]
then
    USERNAME=`cat $REGISTER_DATA/REGISTER_USERNAME`
    PASSWORD=`cat $REGISTER_DATA/REGISTER_PASSWORD`
    SERVERNAME=`cat $REGISTER_DATA/REGISTER_SERVERNAME`
    BUNDLE_ID=`cat $REGISTER_DATA/REGISTER_BUNDLE_ID || true`
    MODE=`cat $REGISTER_DATA/REGISTER_MODE`
    USER=root /usr/share/zentyal/auto-subscribe $USERNAME $PASSWORD $SERVERNAME $BUNDLE_ID $MODE

    # restore .first file that gets deleted during the saveAllModules() when subscribing
    touch /var/lib/zentyal/.first

    if [ -f $REGISTER_DATA/COMMERCIAL_EDITION ]
    then
        apt-get update
        DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y --force-yes zentyal-cloud-prof
    fi
fi
