#!/bin/bash

set -e

if ! getent group ebox-usercorner > /dev/null 2>&1
then
    addgroup --system ebox-usercorner
fi
if ! getent passwd ebox-usercorner > /dev/null 2>&1
then
    adduser --system --home /var/lib/zentyal-usercorner/ \
        --disabled-password --ingroup ebox-usercorner ebox-usercorner
fi

CORNER_LOG="/var/log/zentyal-usercorner/"
test -d $CORNER_LOG || mkdir $CORNER_LOG
chown -R ebox-usercorner:ebox-usercorner $CORNER_LOG

# create user session ids and conf directories
test -d /var/lib/zentyal-usercorner/conf/ || mkdir -p /var/lib/zentyal-usercorner/conf/
test -d /var/lib/zentyal-usercorner/sids/ || mkdir -p /var/lib/zentyal-usercorner/sids/
chown -R ebox-usercorner:ebox-usercorner /var/lib/zentyal-usercorner

# Setup random redis password
REDIS_PASS="/var/lib/zentyal-usercorner/conf/redis.passwd"
if [ ! -f $REDIS_PASS ]; then
    touch $REDIS_PASS
    chmod 0660 $REDIS_PASS
    tr -dc A-Za-z0-9 < /dev/urandom | head -c10 > $REDIS_PASS
fi
chown ebox-usercorner:ebox $REDIS_PASS

# create ebox user corner apache certificates
/usr/share/zentyal/create-certificate /var/lib/zentyal-usercorner/ssl > /dev/null 2>&1 || true

