#!/bin/bash

export http_proxy="192.168.2.1:3128"

echo "HTTP request to $HOST"
wget -t 3 $HOST 2> wget_error

echo "wget error output:"
cat wget_error

echo "Checking for 407 error..."
grep 407 wget_error
