#!/bin/bash

echo "WARNING!!"
echo "All your LDAP data and the Zentyal modules depending on it are going to be erased."
echo "Press Control-C now if you are not sure of what you are doing."
read

service zentyal users stop
(dpkg -l zentyal-samba 2>/dev/null 1>/dev/null && service zentyal samba stop) || true

INSTALLED_MODULES=`dpkg -l | grep 'zentyal-' | grep ^ii | cut -d' ' -f3| xargs`

UNCONFIGURE_MODULES="asterisk egroupware ftp jabber mail samba squid webmail zarafa captiveportal users"

for mod in $UNCONFIGURE_MODULES
do
    (echo $INSTALLED_MODULES | grep -q $mod) || continue
    echo "Unconfiguring module $mod..."
    sudo /usr/share/zentyal/unconfigure-module $mod
done

sudo apt-get -y --force-yes remove --purge slapd
sudo rm -rf /var/lib/ldap* /etc/ldap*

echo "Removal complete. Reinstalling the removed Zentyal modules..."

sudo apt-get update
sudo apt-get -y --force-yes install $INSTALLED_MODULES || exit 1

echo "Done."
echo "Now you can go to 'Users and Groups -> Mode' and configure it again."
