#!/usr/bin/perl
# Copyright (C) 2010-2011 Zentyal S.L.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License, version 2, as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

# This script is intended to rejoin a slave to its master without reinstalling
# Users and Groups module must be configured and enabled, this script will
# communicate with the master and restore the replica
use warnings;
use strict;

use EBox;
use EBox::Global;

EBox::init();
my $users = EBox::Global->modInstance("users");

unless ( $users->mode() eq 'slave' ) {
    print "ERROR: this script is intended for Zentyal Slave machines";
    exit 1;
}

$users->_manageService('stop');

$users->_setupSlaveLDAP(1);

$users->_manageService('start');

$users->save();

1;
