#!/bin/sh

echo "User $USERNAME info..."
ldapsearch -D 'cn=ebox,dc=localdomain' -w $PASSWORD -b "uid=$USERNAME,ou=Users,dc=localdomain"

echo "Checking if $USERNAME has default template..."
ldapsearch -D 'cn=ebox,dc=localdomain' -w $PASSWORD -b "uid=$USERNAME,ou=Users,dc=localdomain" | grep "^egwPermsTemplate: default"
