# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.auto", false);
user_pref("app.update.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1210614970);
user_pref("app.update.lastUpdateTime.background-update-timer", 1210614969);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1210614970);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1210614970);
user_pref("browser.history_expire_days.mirror", 9);
user_pref("browser.preferences.advanced.selectedTabIndex", 0);
user_pref("browser.startup.homepage", "https://127.0.0.1/");
user_pref("browser.startup.homepage_override.mstone", "rv:1.8.1.14");
user_pref("extensions.lastAppVersion", "2.0.0.14");
user_pref("extensions.update.notifyUser", false);
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("pref.browser.homepage.disable_button.current_page", false);
user_pref("remember_mismatched_domains.domain_pairs", "127.0.0.1:eBox%27s%20Server:1A%3A79%3ADF%3A7F%3AC3%3A19%3A16%3A8D%3A38%3A07%3AFD%3A29%3A84%3A35%3A2C%3AB2%3A8F%3A13%3A59%3A22:26%3A5B%3A41%3A39%3A39%3A61%3AC9%3A18%3A56%3AD1%3AC6%3A1B%3A03%3AE8%3A27%3AEA ");
user_pref("security.warn_entering_secure", false);
user_pref("urlclassifier.tableversion.goog-black-enchash", "1.50648");
user_pref("urlclassifier.tableversion.goog-black-url", "1.20892");
user_pref("urlclassifier.tableversion.goog-white-domain", "1.31");
user_pref("urlclassifier.tableversion.goog-white-url", "1.371");
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.103", "");
