#!/bin/bash

set -e

####
## Functions
####

function enable_mod() {
    # This function runs the initial configuration the module needs once it is installed
    systemctl enable --now docker docker.socket
}


####
## Calls
####

enable_mod

exit 0
