#!/bin/bash

set -ex

####
## Functions
####

function initial_conf() {
  # This function runs the initial configuration the module needs once it is installed
  usermod -aG docker $(id -u -n 1000)
}


function mod_disabled() {
    # This function stops and disables the services that uses the module
    systemctl disable --now docker docker.socket
}


####
## Calls
####

initial_conf
mod_disabled

exit 0
