#!/bin/bash

set -e

# Pre-requisites
systemctl disable --now docker
apt remove docker.io docker-doc docker-compose docker-compose-v2 podman-docker containerd runc

# Docker GPG
apt update
apt install ca-certificates curl gnupg
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/trusted.gpg.d/docker.gpg
chmod a+r /etc/apt/trusted.gpg.d/docker.gpg

# Add repo
echo "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/docker.gpg] https://download.docker.com/linux/ubuntu jammy stable" > /etc/apt/sources.list.d/docker.list
apt update

# Docker install
apt install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

exit 0
