#!/bin/bash

set -e

#DEBHELPER#

case "$1" in
    configure)
        # initial setup
        /usr/share/zentyal/initial-setup --no-restart squid $2

        # restart module
        zs squid restart || true

        dpkg-trigger --no-await zentyal-core
    ;;
esac

chown e2guardian:e2guardian /etc/e2guardian
find /etc/e2guardian -type d -exec chmod 750 {} +
find /etc/e2guardian -type f -exec chmod 640 {} +

exit 0
