#!/bin/bash

#DEBHELPER#

case "$1" in
	configure)
		kill `pidof gconfd-2` >/dev/null 2>&1 || true

        # create log table

        # create log table
        /usr/share/ebox/ebox-sql-table add ids /usr/share/ebox/sqllog/ids.sql
        /usr/share/ebox/ebox-sql-table-with-time-period add ids_alert /usr/share/ebox/sqllog/ids_alert.sql

        # restart logs
        invoke-rc.d ebox logs restart || true

        invoke-rc.d ebox ids restart

        dpkg-trigger --no-await ebox
esac

exit 0
