#!/usr/bin/perl

use Mail::IMAPClient;
use IO::Socket::SSL;

my $server = $ENV{SERVER};
my $imapsPort = 993;

my $socket =  IO::Socket::SSL->new("$server:$imapsPort");

$imap = new Mail::IMAPClient( User => 'eboxtest@foobar',
                              Password => 'eboxtest',
                              Socket => $socket,
                              Proto => 'tcp',
                              Port => $imapsPort,
                              Server => $$server,

                              );

if (not $imap->IsConnected()) {
        print "Authentication failed\n";
        exit 1;
} else {
        print "Authentication OK\n";
}

exit 0;
