#!/bin/bash

SERVER=$1
DESKTOP_DIR=`xdg-user-dir DESKTOP`

[ -d $DESKTOP_DIR ] || mkdir $DESKTOP_DIR

create_desktop_link()
{
    LINK="$DESKTOP_DIR/$SHARE.desktop"
    echo "[Desktop Entry]" > $LINK
    echo "Version=1.0" >> $LINK
    echo "Type=Link" >> $LINK
    echo "Name=$SHARE" >> $LINK
    echo "Comment=$DESC" >> $LINK
    echo "URL=smb://$USER@$SERVER/$SHARE" >> $LINK
}

# Create link to the user share
SHARE=$USER
DESC="$USER's share"
create_desktop_link

# Create links to the group shares if they exist
SHARE_GROUPS=`id | tr ',' '\n' | tail -n +3 | cut -d'(' -f2 | cut -d')' -f1`
for i in $SHARE_GROUPS
do
    SHARE=`ldapsearch -x -b "cn=$i,ou=Groups,dc=ebox" -h $SERVER \
           | grep ^displayResource | cut -d: -f2 | cut -c2-`

    if [ -n "$SHARE" ]
    then
        DESC=`ldapsearch -x -b "cn=$i,ou=Groups,dc=ebox" -h $SERVER \
             | grep ^description | cut -d: -f2 | cut -c2-`
        create_desktop_link
    fi
done
