#!/bin/sh

USERHOME=/home/samba/users/$PAM_USER

# Most of this is for debug purposes only

env > $USERHOME/ENV_OUTPUT

PROFILE=$USERHOME/.profile

if ! grep -v ^# $PROFILE | grep -q ID_OUTPUT
then
    echo "id > $USERHOME/ID_OUTPUT" >> $PROFILE
fi

touch $USERHOME/SETUP_SUCCESSFUL
