#!/bin/bash

SERVER=$1

PIDGIN_DIR=$HOME/.ebox-desktop/pidgin

add_conference()
{
    GROUP_NAME=$1

    sed -i "/<group/a\
                <chat proto='prpl-jabber' account='$USER@ebox/eboxuser'>\n\
\t\t\t<component name='handle'>$USER</component>\n\
\t\t\t<component name='room'>$GROUP_NAME</component>\n\
\t\t\t<component name='server'>conference.ebox</component>\n\
\t\t</chat>\n" $PIDGIN_DIR/blist.xml
}

# Replace variables in pidgin config template
sed -i "s/USERNAME/$USER/g" $PIDGIN_DIR/accounts.xml
sed -i "s/EBOXDOMAIN/ebox/g" $PIDGIN_DIR/accounts.xml
sed -i "s/EBOXSERVER/$SERVER/g" $PIDGIN_DIR/accounts.xml
sed -i "s/USERNAME/$USER/g" $PIDGIN_DIR/blist.xml
sed -i "s/EBOXDOMAIN/ebox/g" $PIDGIN_DIR/blist.xml

# Insert group conferences in buddy list
for gid in `id -G`
do
    if [ $gid -ge 2001 ]
    then
        groupname=`getent group $gid | cut -d: -f1`
        add_conference $groupname
    fi
done

mv $PIDGIN_DIR $HOME/.purple
