#!/bin/sh

USERHOME=/home/samba/users/$PAM_USER

# Most of this is for debug purposes only

env > $USERHOME/ENV_OUTPUT

PROFILE=$USERHOME/.profile

if ! grep -v ^# $PROFILE | grep -q ID_OUTPUT
then
    echo "id > $USERHOME/ID_OUTPUT" >> $PROFILE
fi

# Pidgin configuration
sed -i "s/USERNAME/$PAM_USER/g" $USERHOME/pidgin/accounts.xml
sed -i "s/EBOXDOMAIN/ebox/g" $USERHOME/pidgin/accounts.xml
sed -i "s/USERNAME/$PAM_USER/g" $USERHOME/pidgin/blist.xml
sed -i "s/EBOXDOMAIN/ebox/g" $USERHOME/pidgin/blist.xml
mv $USERHOME/pidgin $USERHOME/.purple

touch $USERHOME/SETUP_SUCCESSFUL
