#!/usr/bin/perl -w

# Copyright (C) 2012-2014 Zentyal S.L.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License, version 2, as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

use strict;
use warnings;

# This script is for internal usage only

use EBox;
use EBox::Global;

# Core modules
use TryCatch::Lite;
use Sys::Hostname;

my ($username, $password, $name, $uuid, $mode) = @ARGV;

unless ($username and $password and $name and $uuid) {
    print "Usage: $0 <username> <password> <servername> <bundle_uuid> [mode]\n";
    exit(1);
}

unless ($mode) {
    $mode = 'new';
}

unless (($mode eq 'new') or ($mode eq 'associate') or ($mode eq 'overwrite')) {
    print "Invalid mode: $mode. Choices are: new, associated and overwrite\n";
    exit(2);
}

EBox::init();

my $global = EBox::Global->getInstance();

my $rs = $global->modInstance('remoteservices');

$rs->setUsername($username);
$rs->subscribe($name, $password, $uuid, $mode);

$global->saveAllModules();

1;
