#!/bin/bash

NEW=$1

if [ -z $NEW ]
then
    echo "Usage: $0 <new_hostname>"
    exit 1
fi

CURRENT=`hostname`

sed -i "s/$CURRENT/$NEW/" /etc/hostname
sed -i "s/^$CURRENT\s/$NEW /" /etc/hosts
sed -i "s/\s$CURRENT\s/ $NEW /g" /etc/hosts
hostname $NEW
