#!/bin/bash

db_name=$1
db_user="ebox"

sql_tables_dir=/var/lib/zentyal/sql-tables

create_db()
{
    echo "Creating the $db_name database"
    su postgres -c "createdb $db_name"
    su postgres -c "createuser -R -S -D $db_user"
    su postgres -c "psql -d $db_name -c \"GRANT ALL ON DATABASE $db_name TO $db_user\""

    perl -MEBox -MEBox::LogObserver -e'EBox::init(); EBox::LogObserver::createTables(); 1';
}

# Check if we can connect to postgresql now
su postgres -c 'psql -Alt' >& /dev/null || exit 1

su postgres -c 'psql -Alt' | grep -q "^$db_name|" && db_exists=1 || db_exists=0 || true
if [ $db_exists -eq 0 ]; then
    create_db
    # Create directory to keep track of created tables for each module
    [ -d $sql_tables_dir ] || mkdir $sql_tables_dir
    chown ebox:ebox $sql_tables_dir
fi

touch /var/lib/zentyal/.db-created
