#!/bin/bash

db_name=$1
db_user="ebox"

create_db()
{
    echo "Creating the $db_name database"
    su postgres -c "createdb $db_name"
    su postgres -c "createuser -R -S -D $db_user"
    su postgres -c "psql -d $db_name -c \"GRANT ALL ON DATABASE $db_name TO $db_user\""
    su postgres -c "psql -d $db_name -c \"CREATE LANGUAGE plpgsql\""

    perl -MEBox -MEBox::Util::SQL -e'EBox::init(); EBox::Util::SQL::createCoreTables(); 1';
}

# Check if we can connect to postgresql (with one retry after restart)
su postgres -c 'psql -Alt' >& /dev/null || /etc/init.d/postgresql-8.4 restart
su postgres -c 'psql -Alt' >& /dev/null || exit 1

su postgres -c 'psql -Alt' | grep -q "^$db_name|" && db_exists=1 || db_exists=0 || true
if [ $db_exists -eq 0 ]; then
    create_db
fi

touch /var/lib/zentyal/.db-created
