#!/usr/bin/perl
# Copyright (C) 2011 eBox Technologies S.L.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License, version 2, as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

use EBox;
use EBox::Config;
use EBox::Global;
use EBox::Util::SQL;
use Error qw(:try);

my ($modname) = @ARGV;

EBox::init();

cleanModuleConf($modname);
EBox::Util::SQL::dropModuleTables($modname);

exit 0;

sub cleanModuleConf
{
    my ($module) = @_;

    my $globalConf = "/ebox/modules/global/modules/$module";
    my $moduleConf = "/ebox/modules/$module";

    my $global = EBox::Global->instance();
    $global->delete_dir($globalConf);
    $global->{redis}->delete_dir($moduleConf);
}
