#!/usr/bin/perl
# Copyright (C) 2010-2013 Zentyal S.L.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License, version 2, as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

use warnings;
use strict;

use EBox;
use EBox::Config::Redis;
use EBox::Sudo;
use TryCatch;

my $dir = '';

if ($ARGV[0]) {
    $dir = $ARGV[0];
}

my $editor = 'vi';

if (defined $ENV{VISUAL}) {
    $editor = $ENV{VISUAL};
} elsif (defined $ENV{EDITOR}) {
    $editor = $ENV{EDITOR};
}

EBox::init();

my $redis = EBox::Config::Redis->instance();

my $dumpfile = "/var/lib/zentyal/conf/redisvi-dump-$$";

$redis->export_dir_to_file($dir, $dumpfile, 1);
system("cp $dumpfile $dumpfile.orig");

system("$editor $dumpfile");

system("diff $dumpfile.orig $dumpfile");

if ($? == 0) {
    print "Not modified.\n";
} else {
    $redis->delete_dir($dir);
    try {
        $redis->import_dir_from_file($dumpfile);
    } catch {
        print "Import of modifications failed, restoring the original...\n";
        $redis->rollback();
        $redis->delete_dir($dir);
        $redis->import_dir_from_file("$dumpfile.orig");
    }
}

unlink $dumpfile;
unlink "$dumpfile.orig";
