#!/bin/bash

UPGRADE_FILE=/var/lib/zentyal/.upgrade-finished

rm -f $UPGRADE_FILE

export DEBIAN_FRONTEND=noninteractive

function upgrade
{
    apt-get update

    for i in `seq 1 10`
    do
        if apt-get dist-upgrade -y --force-yes --download-only
        then
            break
        else
            echo "Download failed, retrying in 5 seconds..."
            sleep 5
        fi
    done

    apt-get dist-upgrade -y --force-yes -o DPkg::Options::="--force-confdef"
}

sed -i "s/^deb-src/#deb-src/g" /etc/apt/sources.list

echo; echo "Upgrading your current system to the latest packages..."; echo
upgrade

# Install samba if missing and replicate users with s4sync
/usr/share/zentyal/migrate-users-to-samba

# Stop modules to avoid conflicts in listening ports with haproxy
for module in usercorner captiveportal webserver
do
    service zentyal $module stop > /dev/null 2>&1
done

# Stop slapd
service zentyal users stop

# FIXME: this is for development tests only
sed -i 's/debs-ppa-3.4/debs-ppa/g' /etc/apt/sources.list

echo; echo "Upgrading from Ubuntu 13.10 to 14.04 with Zentyal 3.5..."; echo
sed -i 's/saucy/trusty/g' /etc/apt/sources.list
sed -ri 's/zentyal(.)3.4/zentyal\13.5/g' /etc/apt/sources.list
upgrade

# FIXME: this process needs a lot of refination, this is a temporary workaround
echo; echo "Forcing pending packages installation..."; echo
rm -f /var/lib/dpkg/info/zentyal-core.postinst

for i in `seq 1 3`
do
    apt-get -f install -y --force-yes -o DPkg::Options::="--force-confdef"
    dpkg --configure -a --force-confdef
    apt-get dist-upgrade -y --force-yes -o DPkg::Options::="--force-confdef"
done

if dpkg --configure -a --force-confdef
then
    /usr/share/zentyal/global-action --action saveAllModules

    echo; echo "Zentyal upgrade finished!"

    apt-get clean
else
    echo; echo "Zentyal upgrade failed. Full log at /var/log/zentyal/upgrade.log."
fi

touch $UPGRADE_FILE
