#!/bin/bash

LOG=/var/log/zentyal/upgrade.log
NGINX_UPGRADE_CONF=/var/lib/zentyal/conf/nginx-upgrade.conf

/usr/share/zentyal/upgrade-log-server &

sudo /usr/share/zentyal/shell 'instance webadmin; $webadmin->_setConf();'
echo 'location /ReleaseUpgradeOutput { proxy_pass http://127.0.0.1:1500/; }' > $NGINX_UPGRADE_CONF
sudo systemctl restart zentyal.webadmin-nginx

sleep 5

sudo /usr/share/zentyal/release-upgrade > $LOG 2>&1

rm -f $NGINX_UPGRADE_CONF
