#!/bin/bash

#DEBHELPER#

case "$1" in
	configure)

       # migrate data if needed
       /usr/share/zentyal/ebox-migrate /usr/share/ebox-antivirus/migration/

       # Disable clamd apparmor as it needs some tweaking to make it work with
       # our configuration
       APP_PROFILE="/etc/apparmor.d/usr.sbin.clamd"
       if [ -f $APP_PROFILE ]; then
           sed -i 's:^/usr/sbin/clamd:/usr/sbin/clamd.off:' $APP_PROFILE || true
           /etc/init.d/apparmor restart || true
       fi

       # create directory for freshclam data
       FRESHCLAM_DIR=$(perl -MEBox::AntiVirus -e'print EBox::AntiVirus::freshclamEBoxDir(); 1;');
       mkdir -p $FRESHCLAM_DIR
       chown clamav.clamav $FRESHCLAM_DIR

       # restart logs
       invoke-rc.d zentyal logs restart || true

       # restart module
       invoke-rc.d zentyal antivirus restart

       dpkg-trigger --no-await zentyal-core
esac

exit 0
