#!/bin/bash -e
# 
# boot-sparc v 2.00 (c) Steve Dunham <dunham@cse.msu.edu>, Eric
# Delaunay <delaunay@lix.polytechnique.fr>, Steve McIntyre
# <stevem@chiark.greenend.org.uk>, Ben Collins <bcollins@debian.org>
# Released under GPL 31 Mar 1999
# See the file COPYING for license details
# Released as part of the slink_cd package, not much use standalone
#
# Do install stuff for sparc, including making first CD bootable

set -e

N=$1
CDDIR=$2

cd $CDDIR/..

:> $N.mkisofs_opts

# Only disc 1* bootable
if [ $N != 1 -a $N != 1_NONUS ]; then 
	exit 0; 
fi

echo "-B boot1/boot/second.b boot1" > $N.mkisofs_opts
rm -rf boot1

inst=boot1

# Setup directories
mkdir -p $inst/{boot/sun4{u,cdm},etc}

# put the relevant parts of SILO boot loader
(ar p $MIRROR/dists/$CODENAME/main/binary-sparc/base/silo_* data.tar.gz | \
	tar zxf - -C $inst/ ./boot/{cd,second}.b)

# Some custom etc files
cp -f -p $BASEDIR/tools/boot/potato/sparc-etc/{boot-msg.txt,debian.txt,silo.conf} \
	$inst/etc/

tmp=$TDIR/sparc-root
rm -rf $tmp
mkdir -p $tmp

for suba in sun4cdm sun4u; do
  ln -s ../../dists/$CODENAME/main/disks-$ARCH/current/$suba/linux-a.out \
	$inst/boot/$suba/linux
done

# Unpack the root tree into the directory. we use the tftp root.tar.gz
tar zxf $CDDIR/dists/$CODENAME/main/disks-$ARCH/current/root.tar.gz -C $tmp/
cp -f -a $tmp/debian-sparc-root/. $inst/

# no longer need this
rm -rf $tmp

# Get rid of some junk
rm -f $inst/{boot_message,type.txt}
