#!/bin/bash
#
# boot-i386 v 1.13 (c) Steve McIntyre <stevem@chiark.greenend.org.uk>
# Released under GPL 31 Mar 1999
# 06-10-99 jjw Added $CODENAME and $CODENAME_STATUS support 
#
# Heavily hacked by Raphaël Hertzog <hertzog@debian.org> for
# YACS (the new debian-cd in potato)
# 12MAR00  updated for current i386 bootdisks  --jwest
# 02JAN01  cd1=default-kern, cd2=compact-kern, cd3=idepci-kern --jwest
#
# Do install stuff for i386, including making bootable CDs
#
# $1 is the CD number
# $2 is the temporary CD build dir

set -e

N=$1
CDDIR=$2
BOOTDIR=

cd $CDDIR/..

#
# This script is called with $1 (now $N) as the CD to 
# make bootable.  N may be in the form "n" or "n_NONUS"
# There may be more than 4 disks...support extras.

# Strip stupid NONUS sutff
#
if [ $N = "1_NONUS" ] || [ $N = "1" ] ; then NN=1 ; fi
if [ $N = "2_NONUS" ] || [ $N = "2" ] ; then NN=2 ; fi
if [ $N = "3_NONUS" ] || [ $N = "3" ] ; then NN=3 ; fi
if [ $N = "4_NONUS" ] || [ $N = "4" ] ; then NN=4 ; fi
if [ $N = "5_NONUS" ] || [ $N = "5" ] ; then NN=5 ; fi
if [ $N = "6_NONUS" ] || [ $N = "6" ] ; then NN=6 ; fi
# NN is now 1...N so it can be used as an index

# what kernel-type to put on what disk?
# a null "" value will use the default boot-disk kernel
#
KTYPE[1]=""
KTYPE[2]=compact
KTYPE[3]=idepci
KTYPE[4]="udma66"
KTYPE[5]=""
KTYPE[6]=""

# Show user what is going on.
#
echo "Using ${KTYPE[$NN]} boot-disks image on CD$N"

# Put boot images on CD1...CD(N)
#
:> $N.mkisofs_opts
mkdir -p boot$N/boot
cp -f CD1/dists/$CODENAME/main/disks-$ARCH/current/images-2.88/${KTYPE[$NN]}/rescue.bin boot$N/boot/
echo -n "-J -b boot/rescue.bin -c boot/boot.catalog boot$N"  > $N.mkisofs_opts


# Only disk one gets the extra files installed
#
if [ $N = "1" ] || [ $N = "1_NONUS" ] ; then

# populate the install directory as well
(cd $CDDIR/dists/$CODENAME/main/disks-$ARCH/current/ ; \
	cp -f images-1.44/resc*.bin  $CDDIR/install ; \
	cp -f linux  $CDDIR/install ; \
	cp -f images-1.44/root.bin $CDDIR/install )


##	24-Mar-2000 notes from Ben Collins on using cd as live file-system
##	for 2.2.9 bootdisks	
# (cd $CDDIR/dists/$CODENAME/main/disks-$ARCH/current/images-1.44/ ; \
#	gzip -dc root.bin > /tmp/root.bin.uncompressed ; \
#	mount -o loop /tmp/root.bin.uncompressed /mnt ; \
#	touch /mnt/cdrom_image ; \
#	umount /mnt ; \
#	sync ; \
#	gzip -c9 /tmp/root.bin.uncompressed > $CDDIR/install/root.bin ; \
#	rm /tmp/root.bin.uncompressed  )
## end notes



# Tools for disc 1
# and include the legacy DOS stuff 

cp -f $CDDIR/dists/$CODENAME/main/disks-$ARCH/current/dosutils/* $CDDIR/install/

(echo "Tools for DOS :" ; \
	echo "lodlin/         load Linux kernel from DOS" ;\
	echo "rawrite2/       rawrite 2.0 : create disks from disk images (*.bin)"; \
	) |todos > $CDDIR/tools/README.tools

(echo "@ echo off" ; \
	echo "rem Flush any write-cached disk blocks before we leave DOS. " ; \
	echo "smartdrv /c" ; \
	echo "loadlin.exe linux root=/dev/ram ro initrd=root.bin" ; \
	) |todos > $CDDIR/install/boot.bat
fi
# th,th, thats all
