#!/bin/sh

. /usr/share/debconf/confmodule

db_input high zinstaller-headless/question
db_go
db_get zinstaller-headless/question
if [ "$RET" = "true" ]
then
    debconf-set pkgsel/include zenbuntu-core
fi

exit 0
