#!/bin/bash

echo -n 'X5O!P%@AP[4\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*' > eicar.com

mpack -s 'muahahaha' eicar.com eboxtest@foobar.mail

sleep 2

LOG=/var/log/mail.log

tail $LOG

grep "Blocked INFECTED (Eicar-Test-Signature)" $LOG
