#!/bin/bash

set -e

#DEBHELPER#

case "$1" in
    configure)
        # initial setup
        /usr/share/zentyal/initial-setup --no-restart samba $2

        # restart module
        zs samba restart || true

        dpkg-trigger --no-await zentyal-core
    ;;
    triggered)
        case "$2" in
            "/usr/sbin/samba")
                # Triggered when samba package upgrade, restart module
                zs samba restart || true
            ;;
        esac
    ;;
esac

exit 0
