#!/bin/bash

LOG=/tmp/zentyal-installer.log

# replace motd
cp /usr/share/zenbuntu-desktop/motd /etc/motd.tail

# Import PPA keys to avoid warnings
apt-key add /usr/share/zenbuntu-desktop/zentyal-ppa.asc >> $LOG 2>&1
apt-key add /usr/share/zenbuntu-desktop/zentyal-3.0-archive.asc >> $LOG 2>&1

cp /usr/share/zenbuntu-desktop/first-boot.sh /etc/rc.local

ln -sf /lib/plymouth/themes/zentyal/zentyal.plymouth /etc/alternatives/default.plymouth
ln -sf /lib/plymouth/themes/zentyal-text/zentyal-text.plymouth /etc/alternatives/text.plymouth
ln -sf /lib/plymouth/themes/zentyal/zentyal.grub /etc/alternatives/default.plymouth.grub

if ! grep -q zentyal-lxdm /etc/init/lxdm.conf
then
    sed -i 's/start on/start on zentyal-lxdm and/' /etc/init/lxdm.conf
fi

if [ -f /etc/default/grub ]
then
    if ! grep -q splash /etc/default/grub
    then
        sed -i 's/\(GRUB_CMDLINE_LINUX_DEFAULT=".*\)"/\1 splash"/' /etc/default/grub
        update-grub
    fi
fi
