#!/bin/bash

LOG=/var/tmp/zentyal-installer.log

ln -sf /lib/plymouth/themes/zentyal/zentyal.plymouth /etc/alternatives/default.plymouth
ln -sf /lib/plymouth/themes/zentyal/zentyal.grub /etc/alternatives/default.plymouth.grub

if ! grep -q zentyal-lxdm /etc/init/lxdm.conf
then
    sed -i 's/start on/start on zentyal-lxdm and/' /etc/init/lxdm.conf
fi
