#!/usr/bin/perl
# Copyright (C) 2011-2013 Zentyal S.L.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License, version 2, as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

# Dumps to stdout all group mail aliases

use EBox;
use EBox::Global;
use EBox::Ldap;
use Error qw(:try);

EBox::init();

my $usersMod = EBox::Global->getInstance()->modInstance('users');
my $mailMod = EBox::Global->getInstance()->modInstance('mail');

my @groupsToAdd = $usersMod->groups();

foreach my $group (@groupsToAdd) {
    $groupname = $group->{'account'};
    if ($mailMod->{malias}->groupHasAlias($groupname)) {
        my @groupAlias = @{$mailMod->{malias}->groupAliases($groupname)};
        foreach my $mail (@groupAlias) {
            print "$mail\n";
        }
    }
}

1;
