#!/bin/bash

BUNDLE=$1

function import
{
    echo "FILENAME = $BUNDLE"
}

if [ -n "$BUNDLE" ]
then
    import
    exit $?
fi

# Check if zenity is available (running under X)
zenity 2>/dev/null
if [ $? != 255 ]
then
    echo "Usage: $0 <filename.tar.gz>"
    exit 1
else
    BUNDLE=`zenity --file-selection`
    if [ -n "$BUNDLE" ]
    then
        import
    fi
fi
