#!/bin/sh

VDOMAIN=$1

EGROUPWARE_DB_PASS=/var/lib/ebox/conf/ebox-egroupware.passwd

export EGW_CLI_PASSWORD=`cat $EGROUPWARE_DB_PASS`

cd /usr/share/egroupware/setup

./setup-cli.php --config default,ebox --mailserver localhost,imap,$VDOMAIN,vmailmgr

cd -
