#!/bin/bash

#DEBHELPER#

case "$1" in
	configure)
		# install gconf schemas
		kill `pidof gconfd-2` >/dev/null 2>&1 || true

		# import timezone from system if installing for the first time
		if [ -z "$2" ] ; then
			/usr/share/ebox-ntp/ebox-timezone-import
		fi
           
                # Migrate data if needed
		/usr/share/ebox/ebox-migrate /usr/share/ebox-ntp/migration/

        if [ -z "$EBOX_SOFTWARE" ]; then
		    invoke-rc.d ebox apache restart
        fi
esac



exit 0
