#!/bin/bash
#
# boot-mipsel - (C) 2002 by Karsten Merker <merker@debian.org>
#
# You may copy, modify and distribute this under the terms of the GNU
# General Public License as published by the Free Software Foundation; 
# either version 2 of the License, or (at your option) any later version.
#
# Using this script on any architecture other than mipsel requires
# having binutils-multiarch installed, as it uses objcopy (a part
# of binutils) which is platform dependent. The binutils-multiarch 
# package contains an objcopy which is capable of dealing with other 
# arches' binary formats.
#
# $1 is the CD number
# $2 is the temporary CD build dir

. $BASEDIR/tools/boot/$DI_CODENAME/common.sh

set -e

N=$1
CDROOT=$2
if [ "$DI_WWW_HOME" = "default" ];then
   DI_WWW_HOME="http://people.debian.org/~tbm/d-i/images/mipsel/daily/"
   if [ -n "$DI_DIR" ];then
      DI_DIR="$DI_DIR/~${DI_WWW_HOME#*~}"
      DI_WWW_HOME=""                     
   fi
fi
if [ ! "$DI_DIST" ]; then
   DI_DIST="$DI_CODENAME"
fi

# Strip NONUS part of disk number
# NN will be 1...N so it can be used as an index
#
NN=`echo $N | sed -e 's/_NONUS//'`

cd $CDROOT/..

echo -J > $1.mkisofs_opts

# Only disks 1 bootable
if [ $NN != 1 ]; then
	exit 0
fi

install -m 644 -D $BASEDIR/data/etch/delo.conf "$CDROOT"/etc/delo.conf
install -m 644 -D "$DELOROOT"/boot/delo.2nd "$CDROOT"/boot/delo.2nd

if [ ! "$DI_WWW_HOME" ];then
	if [ ! "$DI_DIR" ];then
	   DI_DIR="$MIRROR/dists/$DI_DIST/main/installer-$ARCH/current/images/cdrom/"
	fi
else
        DI_DIR="."
        wget "$DI_WWW_HOME" -O di.dir
        r3k=$(sed -n 's/.*a href="\(vmlinux-.*-r3k-kn02\)".*/\1/p' di.dir)
        r4k=$(sed -n 's/.*a href="\(vmlinux-.*-r4k-kn04\)".*/\1/p' di.dir)
        wget "$DI_WWW_HOME/$r3k" -O vmlinux-x-r3k-kn02
        wget "$DI_WWW_HOME/$r4k" -O vmlinux-x-r4k-kn04
        wget "$DI_WWW_HOME/initrd.gz"
fi
cp "$DI_DIR"/initrd.gz "$CDROOT/boot/initrd.gz"
cp "$DI_DIR"/vmlinux-*-r3k-kn02 "$CDROOT/boot/vmlinux-r3k-kn02"
cp "$DI_DIR"/vmlinux-*-r4k-kn04 "$CDROOT/boot/vmlinux-r4k-kn04"

install_languages $CDROOT

exit 0
