#!/usr/bin/perl 
# Copyright (C) 2009 EBox Technologies S.L.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License, version 2, as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

use strict;
use warnings;

use EBox;
use EBox::Global;
use EBox::Sudo;

my $srcFile = $ENV{FILE};
$srcFile or
    die 'file parameter not found';
(-r $srcFile) or
    die 'cannot read file';

my $description =  'shalla domain list';



my $path = "/tmp/list.tar.gz";
system "cp $srcFile $path";
($? == 0) or die $!;
system "chown ebox.ebox $path";
($? == 0) or die $!;

EBox::init();


my $squid = EBox::Global->modInstance('squid');
my $filterGroupModel = $squid->model('FilterGroup');
my ($defaultId)      = @{ $filterGroupModel->ids() };
my $row = $filterGroupModel->row($defaultId);
my $policyModel = 
        $row->elementByName('filterPolicy')->foreignModelInstance();
my $domainFilterFiles = $policyModel->componentByName('DomainFilterFiles', 1);

my %params = map {
                  $_->fieldName() => $_ 
                } @{ $domainFilterFiles->_tableHeader() };



$params{description}->setMemValue( { 'description' => $description } );
#$params{fileList}->{dynamicPath} = sub { return $path  };


my $fileId      = $description;
$fileId =~ s/\s/_/g;
my $fileListPath = $domainFilterFiles->listFileDir() . '/' . $fileId;
my $cpCmd =  "cp $path $fileListPath";
EBox::Sudo::root($cpCmd);

$cpCmd =  "cp $path " . $params{fileList}->tmpPath();
EBox::Sudo::root($cpCmd);



$domainFilterFiles->addTypedRow(\%params);


1;
