#!/bin/bash

#DEBHELPER#


case "$1" in
    configure)
        kill `pidof gconfd-2` >/dev/null 2>&1 || true

        # add ebox to lpadmin to manage printers and queues
        adduser --quiet ebox lpadmin
         # add ebox to lp to read cups logs
        adduser --quiet ebox lp

	/usr/share/ebox/ebox-migrate /usr/share/ebox-printers/migration/

        # Restart eBox apache
        invoke-rc.d ebox apache restart || true

     ;;
esac



exit 0
