#!/usr/bin/perl

# Copyright (C) 2012-2013 Zentyal S.L.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License, version 2, as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

use strict;
use warnings;

use EBox;
use EBox::Global;

# Core modules
use Error qw(:try);
use Sys::Hostname;

my ($username, $password, $name, $bundleId) = @ARGV;

unless ($username and $password) {
    print "Usage: $0 <username> <password> [servername [bundle_id]]\n";
    exit(1);
}

unless ($name) {
    $name = hostname();
}

EBox::init();

my $global = EBox::Global->getInstance();

my $rs = $global->modInstance('remoteservices');
my $subscription = $rs->model('Subscription');

my @fields = (username => $username,
              password => $password,
              eboxCommonName => $name);

$subscription->set(@fields);

if ($subscription->showAvailable()) {
    if ($bundleId) {
        push( @fields, options => $bundleId );
        $subscription->reloadTable(); # To notice the change of field
        undef $subscription->{'fields'};
        $subscription->set(@fields);
    } else {
        print "You must provide bundle_id as you have more than one option available\n";
        exit(2);
    }
}

$global->saveAllModules();

1;
