#!/usr/bin/perl

# Copyright (C) 2008-2012 Zentyal S.L.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License, version 2, as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
use strict;
use warnings;
# Description:
#
#  This script is intended to reload the bundle from Zentyal Cloud
#  if the host is subscribed to

use EBox;
use EBox::Exceptions::External;
use EBox::RemoteServices::Exceptions::NotCapable;
use EBox::Event;
use EBox::Gettext;
use EBox::Global;
use Error qw(:try);
use Getopt::Long;
use Pod::Usage;

my ($usage, $force) = (0, 0);
my $correct = GetOptions(
    "usage|help" => \$usage,
    "force"      => \$force,
   );

if ( $usage or (not $correct)) {
    pod2usage(1);
}

EBox::init();
my $global = EBox::Global->getInstance();
my $rs = $global->modInstance('remoteservices');

try {
    my $rv = $rs->reloadBundle($force);
    if ( $rv == 0 ) {
        print STDERR __('Cannot reload the bundle since Zentyal is not connected to the Internet') . "\n";
    } elsif ( $rv == 1 ) {
        print STDOUT __('Bundle reload successfully') . "\n";
    } elsif ( $rv == 2 ) {
        print STDERR __('Bundle reload was not possible either because is already the latest available version or because the zentyal-remoteservices module is outdated') . "\n";
    }
} catch EBox::RemoteServices::Exceptions::NotCapable with {
    my ($exc) = @_;

    print STDERR __x('Cannot reload the bundle: {reason}', reason => $exc->text()) . "\n";
    # Send the event to ZC
    my $evt = new EBox::Event(message     => $exc->text(),
                              source      => 'not-capable',
                              level       => 'fatal',
                              dispatchTo  => [ 'ControlCenter' ]);
    my $evts = $global->modInstance('events');
    $evts->sendEvent(event => $evt);
} catch EBox::Exceptions::External with {
    # Bundle reload it is only possible with a subscribed Zentyal
    ;
};

1;

__END__

=head1 NAME

reload-bundle - Reload bundle sent by Zentyal Remote

=head1 SYNOPSIS

reload-bundle [--usage|help] [--force]

 Options:
   -- usage|help  Print this help and exit

   -- force       Force to reload the bundle although Zentyal may have the latest available version

=cut
