#!/usr/bin/perl

# Copyright (C) 2008-2010 eBox Technologies S.L.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License, version 2, as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

# Description:
#
#  This script is intended to check and store the subscription level
#  and its add-ons from the cloud

use strict;
use warnings;

use EBox;
use EBox::Gettext;
use EBox::Global;
use Getopt::Long;
use Pod::Usage;

my ($usage) = (0);
my $correct = GetOptions(
    "usage|help" => \$usage,
   );

if ( $usage or (not $correct)) {
    pod2usage(1);
}

EBox::init();

my $rs = EBox::Global->modInstance('remoteservices');

$rs->securityUpdatesAddOn('force');
my $disRecOn = $rs->disasterRecoveryAddOn('force');
if ( $disRecOn ) {
    # Reload backup credentials
    $rs->backupCredentials(force => 1);
}
$rs->subscriptionLevel('force');

1;

__END__

=head1 NAME

subs-level - Check the subscription level and the add-ons

=head1 SYNOPSIS

subs-level [--usage|help]

 Options:
   -- usage|help  Print this help and exit

This script "must" be called only from the crontab

=cut
