.\"                                      Hey, EMACS: -*- nroff -*-
.TH ZENTYAL-INSTALL-MODULE 8 "Feb 14 2012"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
zentyal-install-module \- installs a Zentyal module from source
.SH SYNOPSIS
.B zentyal-install-module
.RI [ module ]
.SH DESCRIPTION
This manual page documents briefly the
.B zentyal-install-module
command.
.PP
.B zentyal-install-module
deploys the files of a Zentyal module on its appropiate place from the source.
