# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */
user_pref("mail.account.account1.identities", "id1");
user_pref("mail.account.account1.server", "server1");
user_pref("mail.account.account2.server", "server2");
user_pref("mail.accountmanager.accounts", "account1,account2");
user_pref("mail.accountmanager.defaultaccount", "account1");
user_pref("mail.accountmanager.localfoldersserver", "server2");
user_pref("mail.identity.id1.useremail", "MAILACCOUNT");
user_pref("mail.identity.id1.valid", true);
user_pref("mail.server.server1.authMethod", 0);
user_pref("mail.server.server1.check_new_mail", true);
user_pref("mail.server.server1.hostname", "SERVER");
user_pref("mail.server.server1.realhostname", "SERVER");
user_pref("mail.server.server1.login_at_startup", true);
user_pref("mail.server.server1.max_cached_connections", 5);
user_pref("mail.server.server1.name", "MAILACCOUNT");
user_pref("mail.server.server1.realuserName", "MAILACCOUNT");
user_pref("mail.server.server1.userName", "USER");
user_pref("mail.server.server1.type", "PROTOCOL");
user_pref("mail.server.server1.socketType", "3");
user_pref("mail.smtpserver.smtp1.authMethod", 3);
user_pref("mail.smtpserver.smtp1.hostname", "SERVER");
user_pref("mail.smtpserver.smtp1.port", 25);
user_pref("mail.smtpserver.smtp1.try_ssl", SSL);
user_pref("mail.smtpserver.smtp1.username", "MAILACCOUNT");
user_pref("mail.smtpservers", "smtp1");
user_pref("mail.spam.version", 1);
user_pref("mail.startup.enabledMailCheckOnce", true);

