update-alternatives --force --install /usr/bin/cifsdd cifsdd /opt/samba4/bin/cifsdd 0
update-alternatives --force --install /usr/bin/dbwrap_tool dbwrap_tool /opt/samba4/bin/dbwrap_tool 0
update-alternatives --force --install /usr/bin/eventlogadm eventlogadm /opt/samba4/bin/eventlogadm 0
update-alternatives --force --install /usr/bin/gentest gentest /opt/samba4/bin/gentest 0
update-alternatives --force --install /usr/bin/ldbadd ldbadd /opt/samba4/bin/ldbadd 0
update-alternatives --force --install /usr/bin/ldbdel ldbdel /opt/samba4/bin/ldbdel 0
update-alternatives --force --install /usr/bin/ldbedit ldbedit /opt/samba4/bin/ldbedit 0
update-alternatives --force --install /usr/bin/ldbmodify ldbmodify /opt/samba4/bin/ldbmodify 0
update-alternatives --force --install /usr/bin/ldbrename ldbrename /opt/samba4/bin/ldbrename 0
update-alternatives --force --install /usr/bin/ldbsearch ldbsearch /opt/samba4/bin/ldbsearch 0
update-alternatives --force --install /usr/bin/locktest locktest /opt/samba4/bin/locktest 0
update-alternatives --force --install /usr/bin/masktest masktest /opt/samba4/bin/masktest 0
update-alternatives --force --install /usr/bin/ndrdump ndrdump /opt/samba4/bin/ndrdump 0
update-alternatives --force --install /usr/bin/net net /opt/samba4/bin/net 0
update-alternatives --force --install /usr/bin/nmblookup nmblookup /opt/samba4/bin/nmblookup 0
update-alternatives --force --install /usr/bin/nmblookup4 nmblookup4 /opt/samba4/bin/nmblookup4 0
update-alternatives --force --install /usr/bin/ntlm_auth ntlm_auth /opt/samba4/bin/ntlm_auth 0
update-alternatives --force --install /usr/bin/oLschema2ldif oLschema2ldif /opt/samba4/bin/oLschema2ldif 0
update-alternatives --force --install /usr/bin/pdbedit pdbedit /opt/samba4/bin/pdbedit 0
update-alternatives --force --install /usr/bin/pidl pidl /opt/samba4/bin/pidl 0
update-alternatives --force --install /usr/bin/profiles profiles /opt/samba4/bin/profiles 0
update-alternatives --force --install /usr/bin/regdiff regdiff /opt/samba4/bin/regdiff 0
update-alternatives --force --install /usr/bin/regpatch regpatch /opt/samba4/bin/regpatch 0
update-alternatives --force --install /usr/bin/regshell regshell /opt/samba4/bin/regshell 0
update-alternatives --force --install /usr/bin/regtree regtree /opt/samba4/bin/regtree 0
update-alternatives --force --install /usr/bin/rpcclient rpcclient /opt/samba4/bin/rpcclient 0
update-alternatives --force --install /usr/bin/samba-tool samba-tool /opt/samba4/bin/samba-tool 0
update-alternatives --force --install /usr/bin/sharesec sharesec /opt/samba4/bin/sharesec 0
update-alternatives --force --install /usr/bin/smbcacls smbcacls /opt/samba4/bin/smbcacls 0
update-alternatives --force --install /usr/bin/smbclient smbclient /opt/samba4/bin/smbclient 0
update-alternatives --force --install /usr/bin/smbclient4 smbclient4 /opt/samba4/bin/smbclient4 0
update-alternatives --force --install /usr/bin/smbcontrol smbcontrol /opt/samba4/bin/smbcontrol 0
update-alternatives --force --install /usr/bin/smbcquotas smbcquotas /opt/samba4/bin/smbcquotas 0
update-alternatives --force --install /usr/bin/smbget smbget /opt/samba4/bin/smbget 0
update-alternatives --force --install /usr/bin/smbpasswd smbpasswd /opt/samba4/bin/smbpasswd 0
update-alternatives --force --install /usr/bin/smbspool smbspool /opt/samba4/bin/smbspool 0
update-alternatives --force --install /usr/bin/smbstatus smbstatus /opt/samba4/bin/smbstatus 0
update-alternatives --force --install /usr/bin/smbta-util smbta-util /opt/samba4/bin/smbta-util 0
update-alternatives --force --install /usr/bin/smbtorture smbtorture /opt/samba4/bin/smbtorture 0
update-alternatives --force --install /usr/bin/smbtree smbtree /opt/samba4/bin/smbtree 0
update-alternatives --force --install /usr/bin/tdbbackup tdbbackup /opt/samba4/bin/tdbbackup 0
update-alternatives --force --install /usr/bin/tdbdump tdbdump /opt/samba4/bin/tdbdump 0
update-alternatives --force --install /usr/bin/tdbrestore tdbrestore /opt/samba4/bin/tdbrestore 0
update-alternatives --force --install /usr/bin/tdbtool tdbtool /opt/samba4/bin/tdbtool 0
update-alternatives --force --install /usr/bin/testparm testparm /opt/samba4/bin/testparm 0
update-alternatives --force --install /usr/bin/wbinfo wbinfo /opt/samba4/bin/wbinfo 0

update-alternatives --force --install /usr/sbin/nmbd nmbd /opt/samba4/sbin/nmbd 0
update-alternatives --force --install /usr/sbin/samba samba /opt/samba4/sbin/samba 0
update-alternatives --force --install /usr/sbin/samba_dnsupdate samba_dnsupdate /opt/samba4/sbin/samba_dnsupdate 0
update-alternatives --force --install /usr/sbin/samba_kcc samba_kcc /opt/samba4/sbin/samba_kcc 0
update-alternatives --force --install /usr/sbin/samba_spnupdate samba_spnupdate /opt/samba4/sbin/samba_spnupdate 0
update-alternatives --force --install /usr/sbin/samba_upgradedns samba_upgradedns /opt/samba4/sbin/samba_upgradedns 0
#update-alternatives --force --install /usr/sbin/samba_upgradeprovision samba_upgradeprovision /opt/samba4/sbin/samba_upgradeprovision 0
update-alternatives --force --install /usr/sbin/smbd smbd /opt/samba4/sbin/smbd 0
update-alternatives --force --install /usr/sbin/winbindd winbindd /opt/samba4/sbin/winbindd 0
