#!/bin/bash

# copy LDAP schemas
cp /usr/share/ebox-jabber/*.schema /etc/ldap/schema

# stop jabberd2-ldap-bdb  if it's running as a normal service
invoke-rc.d jabberd2-ldap-bdb  stop

# regenerate slapd.conf
/usr/share/ebox-usersandgroups/ebox-init-ldap genconfig
        
# restart slapd
/etc/init.d/slapd restart

# update current ldap database
/usr/share/ebox-jabber/ebox-jabber-ldap update

exit 0
