AC_DEFUN([AC_CONF_EBOX_CC],
#
# Handle user hints
#
[
  AC_SUBST(VARPATH)
  AC_MSG_RESULT($VARPATH)
  AC_SUBST(CONFPATH)
  AC_MSG_RESULT($CONFPATH)
  AC_SUBST(STUBSPATH)
  AC_MSG_RESULT($STUBSPATH)
  AC_SUBST(CCPATH)
  AC_MSG_RESULT($CCPATH)
  AC_SUBST(LOGPATH)
  AC_MSG_RESULT($LOGPATH)

])
