#!/bin/sh

dd if=/dev/zero of=test.bin bs=4096 count=1000

md5sum test.bin > test.sum

smbclient '\\192.168.2.1\foo' foo -U foo -c 'put test.bin'

rm test.bin

smbclient '\\192.168.2.1\foo' foo -U foo -c 'get test.bin'

md5sum -c test.sum
