#!/bin/sh

PROXY="192.168.2.1:3128"

if [ "x$PASSWORD" != "x" ]
then
    export http_proxy="http://$USERNAME:$PASSWORD@$PROXY/"
else
    export http_proxy="http://$PROXY/"
fi
echo "Using http_proxy=$http_proxy ..."

for i in `seq 1 10`
do
    echo "HTTP request to $HOST"
    wget -t 3 $HOST -O - > wget_output 2>&1
    echo "wget output:"
    cat wget_output
    echo "Looking for $ERROR error..."
    grep $ERROR wget_output
    if [ $? = 0 ]
    then
        echo "Access denied."
        exit 0
    else
        sleep 1
    fi
done

echo "Test failed (timeout)."
exit 1
