#!/usr/bin/perl
# Copyright (C) 2012-2013 Zentyal S.L.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License, version 2, as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

use strict;
use warnings;

use EBox;
use EBox::DBEngineFactory;

my $targetVersion = '3.0';

EBox::init();


my ($version) = @ARGV;
unless ($version le $targetVersion) {
    die "This script is to migrate database from zentyal-log <= $targetVersion ";
}

my $dbEngine = EBox::DBEngineFactory::DBEngine();
my $sqlCmd =  'ALTER TABLE printers_jobs MODIFY COLUMN printer VARCHAR(255);';
$sqlCmd    .= 'ALTER TABLE printers_jobs MODIFY COLUMN username VARCHAR(255);';
print "SQL to execute $sqlCmd\n\n";
$dbEngine->sqlAsSuperuser(sql => $sqlCmd);

1;
