#!/usr/bin/perl
# Copyright (C) 2009 eBox Technologies S.L.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License, version 2, as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

# Script: ebox-remote-ebackup
#
# This script is called from crontab to carry out a full or incremental
# backup depending on the user configuration
#
# It takes one argument that can be:
#
#   --full
#   --incremental
#
#   --full default

use EBox;
use EBox::Global;
use EBox::Sudo;

EBox::init();

my $type = 'full';

if ($ARGV[0] and $ARGV[0] eq '--incremental') {
    $type = 'incremental';
}

my $ebackup = EBox::Global->getInstance(1)->modInstance('ebackup');

if ($type eq 'full') {
    my $removeArguments = $ebackup->remoteDelOldArguments();
    EBox::Sudo::root($removeArguments);
}

my $arguments = $ebackup->remoteArguments($type);
EBox::Sudo::root($arguments);

# Create status
$ebackup->remoteGenerateStatusCache();

# Create file list
my $collection = $ebackup->remoteListFileArguments();
my $tmpFile = $ebackup->tmpFileList();
EBox::Sudo::root("$collection > $tmpFile");
EBox::Sudo::root("chown ebox:ebox $tmpFile");

