#!/bin/bash


#DEBHELPER#

case "$1" in
	configure)
		kill `pidof gconfd-2` >/dev/null 2>&1 || true

 		# create log table
        /usr/share/ebox/ebox-sql-table add leases /usr/share/ebox/sqllog/dhcp.sql
	
		# restart logs
		invoke-rc.d ebox logs restart || true

		# Migrate data if needed
		/usr/share/ebox/ebox-migrate /usr/share/ebox-dhcp/migration/

        # Restart dhcp module
        invoke-rc.d ebox dhcp restart || true
esac



exit 0
