#!/usr/bin/perl
use strict;
use warnings;
use EBox;
use EBox::Global;

EBox::init();

my $module = $ARGV[0];

die "No module name given" unless ($module);

if (EBox::Global->getInstance()->modExists($module)) {
    exit (0);
} else {
    exit (1);
}

