#!/usr/bin/perl

use EBox;
use EBox::Global;
use EBox::ServiceManager;

use Error qw(:try);

my $modName = $ARGV[0];

die "No module name given" unless ($modName);

EBox::init();

my $global = EBox::Global->getInstance();

my $mgr = EBox::ServiceManager->new();

my $module = $global->modInstance($modName);
$module->setConfigured(1);
$module->enableService(1);
$mgr->updateModuleDigests($modName);
try {
    $module->enableActions();
} otherwise {
    my ($ex) = @_;
    $module->setConfigured(0);
    $module->enableService(0);
    EBox::warn("Failed to enable module $modName: " . $ex->text());
}
$mgr->updateModuleDigests($modName);
