#!/usr/bin/perl
use strict;
use warnings;
use EBox;
use EBox::Global;

EBox::init();

my $network = EBox::Global->modInstance('network');

foreach my $iface (@ARGV) {
    if ($network->ifaceExists($iface) {
        $network->set_bool("interfaces/$iface/external", 1);
    }
}

EBox::Global->getInstance()->saveAllModules();

1;

