#!/bin/sh

PASSWORD=$1

echo -n "$PASSWORD" | md5sum - | cut -d' ' -f1 > /var/lib/ebox/conf/ebox.passwd
chown ebox:ebox /var/lib/ebox/conf/ebox.passwd
chmod 600 /var/lib/ebox/conf/ebox.passwd

/etc/init.d/ebox apache restart
