#!/bin/bash

# create log file change owner
touch /var/log/asterisk/cdr-csv/Master.csv
chown asterisk:asterisk /var/log/asterisk/cdr-csv/Master.csv

if [ -d /var/spool/asterisk/ ] ; then
    chown asterisk:asterisk /var/spool/asterisk/
fi
