#!/bin/bash

# create zebra.conf if it does not exist
test -e /etc/quagga/zebra.conf || touch /etc/quagga/zebra.conf
# create zebra.conf if it does not exist
test -e /etc/quagga/ripd.conf || touch /etc/quagga/ripd.conf

