#!/bin/bash

#DEBHELPER#

case "$1" in
    configure)
        # Set proper permissions for /var/run/ebox directory
        chown -R ebox.ebox /var/run/ebox

        # Migrate data if needed
        /usr/share/ebox/ebox-migrate /usr/share/ebox-monitor/migration/

        # Restart the module itself
        invoke-rc.d zentyal monitor restart || true

        dpkg-trigger --no-await zentyal-core
    ;;
esac



exit 0
