#!/bin/bash

#DEBHELPER#

case "$1" in
    configure)
        # Set proper permissions for /var/run/zentyal directory
        chown -R ebox.ebox /var/run/zentyal

        # Migrate data if needed
        /usr/share/zentyal/ebox-migrate /usr/share/zentyal-monitor/migration/

        # Restart the module itself
        invoke-rc.d zentyal monitor restart || true

        dpkg-trigger --no-await zentyal-core
    ;;
esac

exit 0
