#!/bin/bash
#
# boot-hppa
#
# $1 is the CD number
# $2 is the temporary CD build dir

# palo is used to make ISOs bootable on HPPA.

. $BASEDIR/tools/boot/$CODENAME/common.sh

N=$1
CDROOT=$2

:> $1.mkisofs_opts

# Only disk 1* bootable
if [ $N != 1 -a $N != 1_NONUS ]; then
	exit 0
fi

# post-boot script needs iplboot on the image to run palo.  Could
# include iplboot in the bf-image build, but then in might not
# match the local systems version of palo (which may or may not
# matter).

cp -f /usr/share/palo/iplboot $CDROOT/install

install_languages $CDROOT

exit 0

