#!/bin/bash
#
# post-boot-hppa
#
# Do post-image-building tasks for hppa, to make CDs bootable.
#
# $1 is the CD number
# $2 is the temporary CD build dir
# $3 is the image file

set -e

N=$1
CDROOT=$2
CDIMAGE=$3

cd $CDROOT/..

# Only disk 1* bootable
if [ $N != 1 -a $N != 1_NONUS ]; then
	exit 0
fi

/sbin/palo --commandline="0/vmlinux ramdisk_size=8192 root=/dev/ram initrd=0/ramdisk" \
     --recoverykernel=$CDROOT/dists/$CODENAME/main/disks-hppa/current/32/linux.bin \
     --recoverykernel=$CDROOT/dists/$CODENAME/main/disks-hppa/current/64/linux.bin \
     --bootloader=$CDROOT/install/iplboot \
     --ramdisk=$CDROOT/dists/$CODENAME/main/disks-hppa/current/root.bin \
     --init-cdrom=$CDIMAGE --configfile=/dev/null

