#!/bin/bash
#
# post-boot-powerpc 0.1 (C) Daniel Jacobowitz <dan@debian.org>
#
# Released under GPL 10 April 2000
# See the file COPYING for license details
#
# Do post-image-building tasks for powerpc, to make CDs bootable.
#
# $1 is the CD number
# $2 is the temporary CD build dir
# $3 is the image file

set -e

N=$1
CDROOT=$2
CDIMAGE=$3

cd $CDROOT/..

# Only disk 1* bootable
if [ $N != 1 -a $N != 1_NONUS ]; then
	exit 0
fi

case "$MKISOFS" in
    *mkhybrid)
	hmount $3
	hattrib -b ":install:powermac"
	humount $3
    ;;
    *mkisofs)
	exit 0
    ;;
esac
