#!/usr/bin/perl

# Copyright (C) 2005 Warp Networks S.L., DBS Servicios Informaticos S.L.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License, version 2, as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA


use strict;
use warnings;

use EBox;
use EBox::Global;
use EBox::Config;
use HTML::Mason::Interp;

EBox::init();

my $global = EBox::Global->getInstance(1);
my @cmds = ();
my @names = @{$global->modNames};
foreach (@names) {
	my $mod = EBox::Global->modInstance($_);
	push(@cmds, $mod->rootCommands);
}

my $output;
my $interp = HTML::Mason::Interp->new(out_method => \$output);
my $comp = $interp->make_component(comp_file => 
				(EBox::Config::stubs . '/sudo.mas'));
my @array = ();
push(@array, cmds=>\@cmds);
$interp->exec($comp, @array);
print $output;
