#!/usr/bin/perl
use strict;
use warnings;

use EBox;
use EBox::Backup;
use EBox::ProgressIndicator;

use Error qw(:try);

EBox::init();

my %params = @ARGV;
(exists $params{'--progress-id'}) or 
  die 'not progress indicator id supplied';

my $progressId = delete $params{'--progress-id'};


my $progress = EBox::ProgressIndicator->retrieve($progressId);


# put  progress indicator param
$params{progress} = $progress;

try {
  EBox::Backup->makeBackup(%params);
}
otherwise {
  my $ex = shift @_;

 $progress->setAsFinished(1, $ex->text);

  $ex->throw();
};


1;
