#!/usr/bin/perl
# Copyright (C) 2008-2010 eBox Technologies S.L.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License, version 2, as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

use File::Slurp;
use EBox;
use EBox::Exceptions;

if (@ARGV != 1) {
	print "Usage: $0 migration-path";
	exit 1;
}

my $dirh;
my $path = $ARGV[0];

opendir ($dirh, $path) or
    throw EBox::Exceptions::Internal("can't open directory $path");

EBox::init();

foreach my $file (sort(readdir($dirh))) {
	next unless ( -e "$path/$file" );
	next unless ($file =~ /\d\d\d\d.*\.pl/);

    my $file = read_file("$path/$file");
    {
        #silent warnings (redefined subs)
        local $SIG{__WARN__} = sub
        {
            EBox::debug(@_);
        };
        eval $file;
    };

}
