#!/usr/bin/perl

use strict;
use warnings;

use Digest::MD5;


print "EBox\n";
print "Enter new passwd: "; 
&deactivate_echo();
my $passwd1 = <STDIN>;
&activate_echo();
$passwd1 =~ s/[\n\r]//g;

print "Please retype: ";
&deactivate_echo();
my $passwd2 = <STDIN>;
&activate_echo();
$passwd2 =~ s/[\n\r]//g;

if ($passwd1 eq $passwd2) {
	my $ctx = Digest::MD5->new;
	$ctx->add($passwd1);
	my $digest = $ctx->hexdigest;
	print $digest . "\n";
} else {
	print "Wrong input, passwords are different\n";
}

sub  activate_echo(){
	system("/bin/stty echo");
}

sub deactivate_echo(){
	system("/bin/stty -echo");
}
