#!/bin/bash

set -e

case "$1" in
	remove)
        # openvpn changes network interfaces so we must restart network module to propagate the changes
        invoke-rc.d zentyal network restart || true

        dpkg-trigger --no-await zentyal-core
        ;;
    purge)
        /usr/share/zentyal/clean-conf openvpn || true

        /usr/share/zentyal/ebox-sql-table drop openvpn || true
        /usr/share/zentyal/ebox-sql-table drop openvpn_report || true
esac

