#!/bin/bash

# We need to unconfigure and purge module's configuration
# before the gconf schemas have been removed (i.e before gconf
# debhelper has been run). That's why we do things before
# and after gconf debhelper is run
if [ "$1" = "purge" ]; then
	# Purge configuration
	/usr/share/zentyal-core/zentyal-clean-conf mailfilter || true
fi

#DEBHELPER#

case "$1" in
	remove)
        dpkg-trigger --no-await zentyal-core
	;;

	purge)
		/usr/share/zentyal-core/ebox-sql-table drop mailfilter_pop || true
		/usr/share/zentyal-core/ebox-sql-table drop mailfilter_smtp || true
		/usr/share/zentyal-core/ebox-sql-table drop mailfilter_pop_report || true
		/usr/share/zentyal-core/ebox-sql-table drop mailfilter_smtp_report || true
		/usr/share/zentyal-core/ebox-sql-table-with-time-period drop mailfilter_pop_traffic  || true
		/usr/share/zentyal-core/ebox-sql-table-with-time-period drop mailfilter_smtp_traffic  || true
	;;
esac


