#!/bin/bash

/usr/share/zentyal/sql-table add dns_domains /usr/share/zentyal/sqllog/dns_domains.sql
/usr/share/zentyal/sql-table add dns_domains_report /usr/share/zentyal/sqllog/dns_domains_report.sql

chmod g+w /etc/bind

exit 0
