#!/bin/bash

# change owner
if [ -f /var/log/asterisk/cdr-csv/Master.csv ] ; then
    chown asterisk:asterisk /var/log/asterisk/cdr-csv/Master.csv
fi
if [ -d /var/spool/asterisk/ ] ; then
    chown asterisk:asterisk /var/spool/asterisk/
fi
