#!/bin/bash

echo "Expecting foo on $HOST:1100"

for i in `seq 1 30`
do
    nc $HOST 1100 | grep "foo"
    if [ $? != 0 ]
    then
        echo "$i try"
        sleep 1
    else
        echo "Succes"
        exit 0
    fi
done

exit 1
