#!/bin/bash

set -e

#DEBHELPER#


case "$1" in
	configure)

        QUARANTINE_DIR=/var/lib/ebox/quarantine/
        if [ ! -d $QUARANTINE_DIR ]; then
            mkdir -p $QUARANTINE_DIR
        fi
        chmod 730 $QUARANTINE_DIR

        # migrate data if needed
        /usr/share/zentyal/ebox-migrate /usr/share/zentyal-samba/migration/

        #create log tables
        /usr/share/zentyal/ebox-sql-table add samba_access /usr/share/zentyal/sqllog/samba_access.sql
        /usr/share/zentyal/ebox-sql-table add samba_access_report /usr/share/zentyal/sqllog/samba_access_report.sql
        /usr/share/zentyal/ebox-sql-table add samba_virus /usr/share/zentyal/sqllog/samba_virus.sql
        /usr/share/zentyal/ebox-sql-table add samba_virus_report /usr/share/zentyal/sqllog/samba_virus_report.sql
        /usr/share/zentyal/ebox-sql-table add samba_quarantine /usr/share/zentyal/sqllog/samba_quarantine.sql
        /usr/share/zentyal/ebox-sql-table add samba_disk_usage /usr/share/zentyal/sqllog/samba_disk_usage.sql
        /usr/share/zentyal/ebox-sql-table add samba_disk_usage_report /usr/share/zentyal/sqllog/samba_disk_usage_report.sql
        /usr/share/zentyal/ebox-sql-table add samba_virus_share_report /usr/share/zentyal/sqllog/samba_virus_share_report.sql

        dpkg-trigger --no-await zentyal-core
    ;;
esac

exit 0
