#!/bin/bash

# stop daemons
service squid3 stop || true
invoke-rc.d dansguardian stop || true # if dansguardian has not been configured
                                      # it will fail always the first time

# remove startup links
update-rc.d -f dansguardian remove
echo "manual" > /etc/init/squid3.override
