#!/usr/bin/perl
# Copyright (C) 2011-2012 eBox Technologies S.L.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License, version 2, as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

use warnings;
use strict;

use EBox;
use EBox::Global;

EBox::init();
$SIG{PIPE} = 'IGNORE';

print "Upgrading ldap attributes (quotas from mail and users)...\n";

my $users = EBox::Global->modInstance('users');

exit unless defined($users);
exit unless $users->isEnabled();


# Disable default slapd
EBox::Sudo::root(
    'invoke-rc.d slapd stop || true',
    'cp /usr/share/zentyal-users/slapd.default.no /etc/default/slapd'
);

my $BACKUP_DIR = '/var/lib/zentyal/tmp/users-dump';
mkdir $BACKUP_DIR;

$users->dumpConfig($BACKUP_DIR);

my $translucent = "$BACKUP_DIR/translucent-config.ldif";

# rename quota attr in authldap schema
`sed -i "s/NAME 'quota' DESC/NAME 'mailquota' DESC/" $BACKUP_DIR/*-config.ldif`;
`sed -i "s/loginShell \$ quota \$ user/loginShell \$ mailquota \$ user/" $BACKUP_DIR/*-config.ldif`;
`sed -i "s/^quota:/mailquota:/" $BACKUP_DIR/*-data.ldif`;
`test -e $translucent && sed -i "s/olcTranslucentLocal:\\(.*\\),quota,/olcTranslucentLocal:\\1,mailquota,/" $translucent`;

$users->restoreConfig($BACKUP_DIR);

# Perform ldap actions (install new quota schema)
$users->performLDAPActions();

