#!/usr/bin/perl
# Copyright (C) 2011-2012 eBox Technologies S.L.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License, version 2, as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

use warnings;
use strict;

use EBox;
use EBox::Global;
use Error qw(:try);

EBox::init();
$SIG{PIPE} = 'IGNORE';

print "Adding quota objectclasses...\n";

my $users = EBox::Global->modInstance('users');

exit unless defined($users);
exit unless $users->isEnabled();
exit if ($users->mode() eq 'slave');

addSystemQuotasTree($users->ldap(), $users->usersDn());

sub addSystemQuotas
{
    my ($ldap, $dn) = @_;

    my %attrs = (
            base   => $dn,
            filter => "(objectclass=*)",
            attrs  => [ 'objectClass'],
            scope  => 'base'
            );

    my $result = $ldap->ldapCon->search(%attrs);
    my $classes = [ $result->pop_entry()->get_value('objectClass'), 'systemQuotas' ];

    $ldap->modify($dn,
        { 'changes' => [ 'replace' => [ 'objectClass' => $classes ] ]} );
}

sub addSystemQuotasTree
{
    my ($ldap, $dn) = @_;

    my %attrs = (
            base   => $dn,
            filter => "(uid=*)",
            attrs  => [ 'objectClass'],
            scope  => 'sub'
    );
    my $result = $ldap->ldapCon->search(%attrs);
    for my $entry ($result->entries()) {
        addSystemQuotas($ldap, $entry->dn());
    }
}



