#!/usr/bin/perl
# Copyright (C) 2011-2012 eBox Technologies S.L.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License, version 2, as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

use strict;
use warnings;

use EBox;
use EBox::Validate;
use EBox::Global;
use EBox::Ldap;

print "Migrating fetchmail accounts\n";

EBox::init();
my $users = EBox::Global->getInstance()->modInstance('users');
my $ldap  = $users->ldap();

my %attrs = (
        base => EBox::Global->modInstance('users')->usersDn,
        filter => 'objectclass=fetchmailUser',
        scope => 'sub'
       );

my $result = $ldap->search(\%attrs);
if ($result->count() == 0) {
    print "No fetchamil accounts to migrate\n";
    exit 0;
}

my %validProtocols = (
    pop3 => 1,
    imap  => 1,

   );

foreach my $entry ($result->entries()) {
    my @accounts = $entry->get_value('fetchmailAccount');
    if (not @accounts) {
        next;
    }

    my @newAccounts;
    foreach my $oldStr (@accounts) {
        my @parts = split ':', $oldStr, 6;
        my $user         = $parts[0];
        my $password     = $parts[1];
        my $mailProtocol = $parts[2];
        my $server       = $parts[3];
        my $port         = $parts[4];
        my $options = '';
        if ($parts[5]) {
            # ssl option
            $options        =  'ssl';
        }

        my $newStr = join ':', ($user, $mailProtocol, $server, $port, $options, $password);
        my $accountOk = 1;
        if (not $port =~ m/^\d+$/) {
            $accountOk = 0;
            print "Bad fetchmailAccount: '$oldStr'  (invalid port)\n";
        } elsif (not $validProtocols{$mailProtocol} ) {
            $accountOk = 0;
            print "Bad fetchmailAccount: '$oldStr'  (invalid protocol)\n";
        }

        if ($accountOk) {
            push @newAccounts, $newStr;
        }

    }
    if (@newAccounts) {
        $entry->replace('fetchmailAccount' => \@newAccounts);
    } else {
        $entry->delete('fetchmailAccount');
    }

    $entry->update($ldap->ldapCon());
#    print qq{Replaced "@accounts" with "@newAccounts"\n};
}

print "DONE\n";

1;
