#!/bin/bash

# stop and disable cups
invoke-rc.d cups stop
update-rc.d cups disable

# create spool
if [ ! -d /var/spool/samba ]; then
    mkdir /var/spool/samba
    chown nobody:nogroup /var/spool/samba
    chmod a+rwt /var/spool/samba
fi

# Set permissions for printer drivers
chown -R root:512 /var/lib/samba/printers
chmod -R g+w /var/lib/samba/printers

