#!/bin/bash
#
# boot-hppa
#
# $1 is the CD number
# $2 is the temporary CD build dir

# palo is used to make ISOs bootable on HPPA.

. $BASEDIR/tools/boot/$DI_CODENAME/common.sh

set -e

N=$1
CDROOT=$2
if [ "$DI_WWW_HOME" = "default" ];then
   DI_WWW_HOME="http://people.debian.org/~jbailey/d-i/hppa/daily/cdrom/2.6"
   if [ -n "$DI_DIR" ];then
      DI_DIR="$DI_DIR/~${DI_WWW_HOME#*~}"
      DI_WWW_HOME=""                     
   fi
fi
if [ ! "$DI_DIST" ]; then
   DI_DIST="$DI_CODENAME"
fi

:> $1.mkisofs_opts

# Only disk 1* bootable
if [ $N != 1 -a $N != 1_NONUS ]; then
	exit 0
fi

PALODEB="$($BASEDIR/tools/apt-selection cache show palo | \
	sed -n 's/^Filename: \(.*_hppa.deb\)$/\1/p')"
ar p "${MIRROR}/${PALODEB}" data.tar.gz | tar xz ./usr/share/palo/iplboot
mv usr/share/palo/iplboot $CDROOT/install/iplboot

if [ ! "$DI_WWW_HOME" ];then
        if [ ! "$DI_DIR" ];then
           DI_DIR="$MIRROR/dists/$DI_DIST/main/installer-$ARCH/current/images/cdrom/2.6"
        fi
else
	DI_DIR="di_stuff"
	mkdir "$DI_DIR"
	wget -r -nd --no-parent -P "$DI_DIR" "$DI_WWW_HOME"
fi
	
cp "$DI_DIR"/vmlinux-*-32 "$CDROOT/install"
cp "$DI_DIR"/vmlinux-*-64 "$CDROOT/install"
cp "$DI_DIR"/initrd.gz "$CDROOT/install"

install_languages "$CDROOT"

exit 0
