#!/bin/bash -x

# generate certificates
# FIXME: temporary disabled to avoid conflict with PostgreSQL
#cp /usr/share/doc/freeradius/examples/certs/* /etc/freeradius/certs/
#cd /etc/freeradius/certs/ ; ./bootstrap
