#!/usr/bin/perl

use strict;
use warnings;


use Getopt::Long;
use Cwd;
use HTML::Mason;
use File::Slurp;

use constant 
    {
       MODULE_VERSION => '0.1',
       STUBS_PATH => '/home/magnetic/dev/ebox/sources/trunk/extra/moddev/stubs',
    };

sub _printUsage
{
    print STDERR "Usage: $0 --module-name --main-class [Options]\n\n";
    print STDERR "Options:\n";
    print STDERR "\t--version\n"; 
    print STDERR "\t--destdir\n";
    exit 1;
}

sub _parseOptions
{
    my %options = ( 
            moduleName => undef, 
            mainClass => undef ,
            version => MODULE_VERSION,
            destdir => undef,
            );
    my $help;
    my $info;
    my $optionsOk = GetOptions(
            'module-name=s' => \$options{moduleName},
            'main-class=s' => \$options{mainClass},
            'version=s' => \$options{version},
            'destdir=s' => \$options{destdir},
            'help'  => \$help,
            'info'  => \$info,
            );

    if (not $optionsOk or $info or $help) {
        _printUsage();
    }

    unless (defined($options{moduleName}) and defined($options{mainClass})) {
        _printUsage();
    }

    if ($options{destdir}) {
        unless (-d $options{destdir}) {
            die "$options{destidir} does not exist";
        }
    } else {
        $options{destdir} = getcwd;
    }

    $options{destdir} .= '/' . $options{moduleName};

    if ( -d $options{destdir} ) {
        die "$options{destdir} already exists!!";
    }

    return \%options;
}

sub _createModule
{
    # Main
    my %options = %{_parseOptions()};

    my $dir = $options{destdir};
    
    mkdir $dir or die "Can't create dir $dir";
    
    my $stubs = STUBS_PATH;
    my $output;
    my $interp = HTML::Mason::Interp->new(comp_root => $stubs, 
            out_method => \$output);


    # configure.ac
    my $comp = $interp->make_component(comp_file => "$stubs/configure.ac.mas");
    $interp->exec($comp,  
            (mainClass => $options{mainClass},
             module => $options{moduleName},
             version => $options{version}));
   write_file("$dir/configure.ac", $output);

   # Makefile.am 
   $output = '';
   $comp = $interp->make_component(comp_file => "$stubs/Makefile.am.mas");
   $interp->exec($comp);
   write_file("$dir/Makefile.am", $output);

}

_createModule();
