#!/bin/bash

echo "Checking if $DIR exists..."

if ! [ -d $DIR ]
then
    echo "Not exists, creating..."
    mkdir -p $DIR
else
    echo "Already exists."
fi    

echo "Creating $DIR/index.html"

echo "foo" > $DIR/index.html
