#!/bin/bash

echo "Setting the proxy..."
export http_proxy="192.168.2.1:3128"

for i in `seq 1 10`
do
    [ -f output.html ] && rm output.html

    echo "HTTP request to $HOST"
    wget -t 3 $HOST -O output.html > wget_output 2>&1

    echo "wget output:"
    cat wget_output

    echo "Checking if access was denied"
    grep "Access has been Denied" output.html

    if [ $? = 0 ]
    then
        echo "Access denied."
        exit 0
    else
        sleep 2
    fi
done

echo "Test failed (timeout)."
exit 1
