#!/bin/bash

for i in `seq 1 24`
do
    if grep "$EVENT" /var/log/ebox/ebox.log
    then
        echo "Test succeded"
        exit 0
    else
        sleep 5
    fi
done

echo "Test failed by timeout"
exit 1
