#!/bin/sh

# Check latest version
URL="http://update.zentyal.org/last-3.0.txt"
TIMEOUT="300"
DEST="/var/lib/zentyal/latestversion"
wget --timeout $TIMEOUT $URL -O $DEST >/dev/null 2>&1

# Gather reporting info
/usr/share/zentyal/gather-reportinfo
# Consolidate this reporting info
/usr/share/zentyal/consolidate-reportinfo
